#Requires -Version 7.0
# fuaran — the pure tier's structural-predicate LAWS, run on BOTH pipelines (Phase 443 follow-up).
#
# WHY THIS EXISTS. The repo's only Fable leg — `dotnet run --project Build.fsproj -- Catalog` — is a
# COMPILE gate. It proves the pure tier transpiles; it makes no claim about whether the transpiled
# algebra still obeys its laws, and nothing in a .NET test suite can make that claim either. So the
# laws `Fuaran.UI.Tests` enumerates on .NET had no counterpart under Node at all, and the one
# session that ran them there did it by hand.
#
# THE LAWS ARE DEFINED ONCE, in `Laws.fs` beside this script. That file is compiled by BOTH
# executors — `Program.fs` here, which this script runs on both pipelines, and the Expecto suite in
# `src/Fuaran.UI.Tests`, which links it. Neither owns a law, so an edit to one reddens both. Until
# that seam existed the laws were written out twice and the copies had already drifted: this side
# enumerated the cubic laws over five of the eleven pool members and checked neither absorption nor
# distributivity, which made "the laws hold on both pipelines" a statement about two different sets
# of laws. Add a law to `Laws.laws` and it appears here and in that suite in the same edit.
#
# It makes TWO claims, and they are different:
#   1. the laws hold under Node, over the shared corpus;
#   2. the two pipelines agree about every MATCH SET, because the runs are byte-compared and each
#      line carries per-predicate set SIZES rather than a bare law verdict. A law-only probe would
#      report two disagreeing pipelines as two green runs.
#
# NOT wired into run.ps1 or the FAKE targets, on purpose — it needs a Node runtime and the default
# gate is deliberately dependency-free. The same posture as tests/ids-parity-probe beside it. Run it
# after touching StructuralQuery, the decoder, or anything in the pure tier's collection handling.
#
# Exit 0 = both pipelines emitted byte-identical output AND reported zero law violations.
[CmdletBinding()]
param(
    # Keep the generated corpus module, the emitted JS and the two captured outputs for inspection.
    [switch] $KeepOutput
)

$ErrorActionPreference = 'Stop'
Set-Location $PSScriptRoot

if (-not (Get-Command node -CommandType Application -ErrorAction SilentlyContinue)) {
    Write-Host '==== pure-tier laws: SKIPPED — no `node` on PATH (this probe needs a JS runtime)' -ForegroundColor Yellow
    exit 0
}

# ── 1. Generate the corpus module ───────────────────────────────────────────
#
# Fable cannot read a file, so the corpus is compiled IN. Generating it on every run is what makes
# the two pipelines provably see identical input: a probe that let each side load the corpus its own
# way would be comparing two loaders as well as two algebras.
#
# Absence of the corpus is a HARD FAILURE here, not a skip. This is a conformance probe against a
# shared oracle, and a conformance check that goes green without its oracle is worse than none.

$nodesDir = Join-Path $PSScriptRoot '..' '..' '..' 'wire-format-fixtures' 'nodes'

if (-not (Test-Path $nodesDir)) {
    Write-Host "==== pure-tier laws: FAILED — corpus not found at $nodesDir" -ForegroundColor Red
    Write-Host '     The shared wire-format-fixtures/ clone is the oracle for this probe. Clone it beside the repo.'
    exit 1
}

$fixtures = Get-ChildItem -Path $nodesDir -Filter '*.json' | Sort-Object Name

if ($fixtures.Count -eq 0) {
    Write-Host "==== pure-tier laws: FAILED — no fixtures under $nodesDir" -ForegroundColor Red
    exit 1
}

$sb = [Text.StringBuilder]::new()
[void]$sb.AppendLine('module PureTierLaws.Corpus')
[void]$sb.AppendLine()
[void]$sb.AppendLine('// GENERATED by run-pure-tier-laws.ps1 from wire-format-fixtures/nodes/. Do not edit; do not commit')
[void]$sb.AppendLine('// (it is gitignored). Regenerated on every run so both pipelines compile in the same bytes.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('let fixtures: (string * string) list =')
[void]$sb.AppendLine('    [')

foreach ($f in $fixtures) {
    $name = [IO.Path]::GetFileNameWithoutExtension($f.Name)
    $json = ([IO.File]::ReadAllText($f.FullName)).Trim()

    # A triple-quoted F# string takes JSON verbatim — JSON cannot contain `"""` unescaped, so the
    # delimiter is safe by the format's own rules rather than by hoping.
    if ($json.Contains('"""')) {
        Write-Host "==== pure-tier laws: FAILED — fixture $name contains a triple-quote; the generator's delimiter is unsafe" -ForegroundColor Red
        exit 1
    }

    [void]$sb.AppendLine("        `"$name`", `"`"`"$json`"`"`"")
}

[void]$sb.AppendLine('    ]')

$corpusFile = Join-Path $PSScriptRoot 'Corpus.g.fs'
[IO.File]::WriteAllText($corpusFile, $sb.ToString())
Write-Host "==== pure-tier laws: generated Corpus.g.fs from $($fixtures.Count) fixtures"

$outDir = Join-Path $PSScriptRoot 'out'
Remove-Item -Recurse -Force $outDir -ErrorAction SilentlyContinue

function Remove-Generated {
    if (-not $KeepOutput) {
        Remove-Item -Force $corpusFile -ErrorAction SilentlyContinue
        Remove-Item -Recurse -Force $outDir -ErrorAction SilentlyContinue
    }
}

# ── 2. The .NET side ────────────────────────────────────────────────────────
#
# Filter to the probe's own line shapes so build chatter can never enter the comparison.

$lineShape = '^(FIX|LAW|POOL|TOTAL) '

$dotnetOut = (dotnet run --project PureTierLaws.fsproj) | Where-Object { $_ -match $lineShape }

if ($LASTEXITCODE -ne 0 -and $dotnetOut.Count -eq 0) {
    Write-Host '==== pure-tier laws: the .NET run FAILED to produce output' -ForegroundColor Red
    Remove-Generated
    exit 1
}

# ── 3. The transpiled side ──────────────────────────────────────────────────
#
# `dotnet fable` needs no npm/npx, so the workspace Invoke-Npm convention does not apply; `node` is
# a real executable, not a PowerShell shim.

dotnet fable PureTierLaws.fsproj -o $outDir --noCache | Out-Null

if ($LASTEXITCODE -ne 0) {
    Write-Host '==== pure-tier laws: the Fable compile FAILED' -ForegroundColor Red
    Remove-Generated
    exit 1
}

$fableOut = (node (Join-Path $outDir 'Program.js')) | Where-Object { $_ -match $lineShape }

# ── 4. Compare ──────────────────────────────────────────────────────────────

if ($dotnetOut.Count -eq 0 -or $fableOut.Count -ne $dotnetOut.Count) {
    # A count mismatch means one side did not produce the corpus at all. Reporting that as "0
    # divergences" would be a vacuous green, so it is a failure in its own right.
    Write-Host "==== pure-tier laws: FAILED — .NET emitted $($dotnetOut.Count) lines, Fable emitted $($fableOut.Count)" -ForegroundColor Red
    Remove-Generated
    exit 1
}

$diverged = @(0..($dotnetOut.Count - 1) | Where-Object { $dotnetOut[$_] -cne $fableOut[$_] })

if ($diverged.Count -gt 0) {
    Write-Host "==== pure-tier laws: FAILED — $($diverged.Count) of $($dotnetOut.Count) lines diverge between the pipelines" -ForegroundColor Red
    Write-Host '     (.NET is the canonical side)'
    foreach ($i in $diverged | Select-Object -First 10) {
        Write-Host "       .NET  $($dotnetOut[$i])"
        Write-Host "       Fable $($fableOut[$i])"
    }
    if ($diverged.Count -gt 10) { Write-Host "       … and $($diverged.Count - 10) more" }
    Remove-Generated
    exit 1
}

# Both sides are byte-identical, so reading the .NET summary reads both.

$total = $dotnetOut | Where-Object { $_ -match '^TOTAL ' } | Select-Object -Last 1
$poolLine = $dotnetOut | Where-Object { $_ -match '^POOL ' } | Select-Object -Last 1

if (-not $total) {
    Write-Host '==== pure-tier laws: FAILED — no TOTAL line; the probe did not run to completion' -ForegroundColor Red
    Remove-Generated
    exit 1
}

if ($total -notmatch 'violations=(\d+)') {
    Write-Host "==== pure-tier laws: FAILED — unreadable summary line: $total" -ForegroundColor Red
    Remove-Generated
    exit 1
}

$violations = [int]$Matches[1]

# A pool member that matches everywhere or nowhere makes every law a statement about a constant.
# Checked here rather than trusted, so the run cannot be green and vacuous at the same time.
if ($poolLine -match '(never|always)') {
    Write-Host "==== pure-tier laws: FAILED — a pool predicate does not discriminate over the corpus" -ForegroundColor Red
    Write-Host "       $poolLine"
    Remove-Generated
    exit 1
}

if ($violations -ne 0) {
    Write-Host "==== pure-tier laws: FAILED — $violations law violation(s) on BOTH pipelines" -ForegroundColor Red
    Write-Host "       $total"
    Remove-Generated
    exit 1
}

if ($KeepOutput) {
    Set-Content -Path (Join-Path $PSScriptRoot 'laws-dotnet.txt') -Value $dotnetOut
    Set-Content -Path (Join-Path $PSScriptRoot 'laws-fable.txt') -Value $fableOut
}

Remove-Generated

Write-Host "==== pure-tier laws: green — $($dotnetOut.Count) lines byte-identical on both pipelines" -ForegroundColor Green
Write-Host "     $total"
exit 0
