<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="InboundTests.fs" />
    <Compile Include="ConnTokenTests.fs" />
    <Compile Include="SseChannelTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fuaran.UI.ServerDriven.AspNetCore\Fuaran.UI.ServerDriven.AspNetCore.fsproj" />
    <ProjectReference Include="..\Fuaran.UI.ServerDriven\Fuaran.UI.ServerDriven.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Expecto" />
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>
</Project>
