module Fuaran.UI.Tests.EnumTokenTests

// ============================================================================
//  Phase 1691 — the enum case-to-wire-token table, made undeniable.
//
//  SIX of this vocabulary's forty-six closed bare-string enums do NOT encode as
//  their bare case name: `LinkProtection`, `TextDirection`, `TextFormat`,
//  `CompareOp`, `SortDirection`, `LiveRegionKind`. An emitter that derives the
//  token from the case name therefore COMPILES, and emits `"Polite"` where the
//  corpus says `"polite"` — wrong in the direction that still builds. Phase 1657
//  found it by perturbing a committed tree and re-running, not by any gate.
//
//  WHAT WAS ALREADY TRUE BEFORE THIS PHASE, stated so the value of what is here
//  is not overclaimed. The mapping already had ONE HOME: `Vocabulary.fs`
//  declares it (`Declare.enumWith` for the six, `Declare.enumOf` for the forty),
//  `idl.json` renders it, and `WIRE_FORMAT.md` 3.5 is a marker-fenced projection
//  of that same file, regenerated by `--project-spec` and gated by
//  `--check-spec`. So the DECLARATION → SPEC axis was covered.
//
//  What was NOT covered, and what this file is, is the DECLARATION →
//  IMPLEMENTATION axis. 3.5 states the wire side alone and carries no host-case
//  column, so it cannot answer "which case does this token belong to"; and
//  nothing anywhere asserted that any of the six independent surfaces in this
//  repo that SPELL a token agree with the declaration. They are, with what pins
//  each one here:
//
//    * the generated encoder + decoder (`Fuaran.UI.Generated`) — driven, per
//      case, through reflection over the real compiled functions;
//    * the hand-written policy decoder (`Fuaran.UI.Ops.JsonDecode`) — same;
//    * the JSON Schema (`Fuaran.UI.Ops.SchemaGen`, which emits the corpus's
//      `schema.json`) — its `enum` arrays compared to the table;
//    * `Fuaran.UI.RenderFidelity.liveRegionToken` (which feeds the corpus's
//      `render-fidelity.json`);
//    * the corpus artefact `enum-tokens.json` itself.
//
//  Two surfaces are deliberately NOT pinned here, and both are named rather than
//  left silent: `TreeMerge.directionToken` already has its own
//  `StyleFacetTokenTests`, and the `CompareOp` match inlined in
//  `Fuaran.UI.Renderer/Render.fs` renders a host-side DOM attribute from a
//  private local with no reachable seam.
//
//  THE GO-RED. Flip one token in `src/Fuaran.UI.Idl/Vocabulary.fs` (say
//  `LiveRegionKind`'s `"assertive"` to `"loud"`) and regenerate: the corpus pin,
//  the generated-encoder arm, the decoder arms and the schema arm all fail, each
//  naming the enum and the case. Flip it in the corpus alone and the pin fails.
//  Flip it in `SchemaGen.fs` alone and the schema arm fails. There is no edit to
//  one of these surfaces that leaves the others silently disagreeing.
//
//  VACUITY. Every reflective arm counts what it exercised and asserts a floor,
//  because a reflective lookup that finds nothing passes every assertion it
//  makes. The floors are stated as the counts standing when this phase shipped;
//  they may only grow.
// ============================================================================

open System
open System.IO
open System.Reflection
open System.Text.Json
open Expecto
open Microsoft.FSharp.Reflection
open Fuaran.Tests.EnumTokens

// ─── the table, from the TYPED vocabulary ──────────────────────────────────

/// The table as the homed declaration states it — `IdlCertification.vocabulary`
/// is `Fuaran.UI.Vocabulary.uiIdl` in the canonicalised shape the committed
/// `idl.json` is emitted from, so this and the parsed artefact are comparable
/// without either being derived from the other.
let private typedTable: EnumTokenEntry list =
    IdlCertification.vocabulary.Enums
    |> List.map (fun e ->
        { Name = e.Name
          Mapped = not (List.isEmpty e.Wires)
          Cases = e.Cases |> List.map (fun c -> c, e.WireOf c) })
    |> order

/// The six the phase names. Written out rather than derived, deliberately: this
/// is the ASSERTION that the mapped set is exactly these, so deriving it from
/// the same value it checks would make it true by construction and say nothing.
let private theSix =
    [ "CompareOp"
      "LinkProtection"
      "LiveRegionKind"
      "SortDirection"
      "TextDirection"
      "TextFormat" ]

let private repoRoot () = Fuaran.Tests.CorpusRoot.tryRepoRoot ()

// ─── reflection helpers ────────────────────────────────────────────────────

let private uiAssembly = typeof<Fuaran.UI.Generated.BadgeVariant>.Assembly
let private opsAssembly = typeof<Fuaran.UI.Ops.JsonDecode.DecodeError>.Assembly

let private moduleType (asm: Assembly) (name: string) : Type =
    match asm.GetType name |> Option.ofObj with
    | Some t -> t
    | None -> failtestf "the module type '%s' is not in %s — this suite drives it by reflection" name asm.FullName

let private staticMethod (t: Type) (name: string) : MethodInfo option =
    t.GetMethod(name, BindingFlags.Static ||| BindingFlags.Public ||| BindingFlags.NonPublic)
    |> Option.ofObj

/// Reflection's boxing contract is `objnull` and F# 10's is `obj`; launder in
/// the one place, the `Unchecked.nonNull` idiom this repo already uses at every
/// other reflection seam.
let private nn (v: 'T) : obj = box v |> Unchecked.nonNull

/// A union case value built by name, for driving an encoder that takes one.
let private unionCase (t: Type) (case: string) : obj =
    match FSharpType.GetUnionCases(t, true) |> Array.tryFind (fun c -> c.Name = case) with
    | Some c -> FSharpValue.MakeUnion(c, [||], true) |> Unchecked.nonNull
    | None -> failtestf "%s has no case '%s' — the declared vocabulary and the generated type disagree" t.Name case

/// Invoke a static method reflectively, laundering the nullable return.
let private invoke (m: MethodInfo) (args: obj list) : obj =
    m.Invoke(null, args |> List.map (fun a -> (a: objnull)) |> List.toArray)
    |> Unchecked.nonNull

/// The case name of a union value, for reading a decoder's result.
let private caseNameOf (v: obj) : string =
    let case, _ = FSharpValue.GetUnionFields(v, v.GetType() |> Unchecked.nonNull, true)
    case.Name

/// `JStr s` from `Fuaran.Core` — the value type the generated codecs speak.
/// Typed rather than reflective: the type is on this suite's own reference
/// graph, so nothing is gained by reaching it through strings.
let private jStr (s: string) : obj = nn (Fuaran.Core.JStr s)

let private jStrValue (v: obj) : string option =
    match v :?> Fuaran.Core.JVal with
    | Fuaran.Core.JStr s -> Some s
    | _ -> None

/// `Result` shape reading, for both codecs' `Result<_, _>` returns.
let private resultOk (v: obj) : obj option =
    let case, fields =
        FSharpValue.GetUnionFields(v, v.GetType() |> Unchecked.nonNull, true)

    if case.Name = "Ok" then
        Some(Unchecked.nonNull fields[0])
    else
        None

// ─── the arms ──────────────────────────────────────────────────────────────

let private declarationArm =
    testList
        "the declaration is the one home"
        [ test "the table parsed from the committed idl.json equals the typed vocabulary" {
              match repoRoot () with
              | None -> skiptest "repo root not found from the test binary (Fuaran.sln absent walking up)"
              | Some root ->
                  let authored = Path.Combine(root, "src", "Fuaran.UI.Idl", "idl.json")
                  Expect.isTrue (File.Exists authored) (sprintf "the authored vocabulary exists at %s" authored)

                  Expect.equal
                      (ofIdlJson (File.ReadAllText authored))
                      typedTable
                      "src/Fuaran.UI.Idl/idl.json disagrees with src/Fuaran.UI.Idl/Vocabulary.fs about the enum tokens. Regenerate with `FUARAN_REGEN=1 dotnet run --project src/Fuaran.UI.Idl.Tests`."
          }

          test "exactly six enums declare a non-identity mapping, and they are the six" {
              Expect.equal
                  (typedTable
                   |> List.filter (fun e -> e.Mapped)
                   |> List.map (fun e -> e.Name)
                   |> List.sort)
                  theSix
                  "the set of enums whose wire token is not their case name has changed. A NEW one is not a defect — it is a declaration, and this list is where it is acknowledged; a MISSING one means a mapping was silently dropped to the identity, which is the Phase 1657 failure in reverse."
          }

          test "every identity enum's tokens are its case names" {
              let offenders =
                  typedTable
                  |> List.filter (fun e -> not e.Mapped)
                  |> List.collect (fun e ->
                      e.Cases |> List.filter (fun (c, t) -> c <> t) |> List.map (fun p -> e.Name, p))

              Expect.isEmpty
                  offenders
                  "an enum declaring no mapping carries a token that is not its case name — the artefact's `mapped:false` would then be a lie to every consumer reading it"
          }

          test "the mapped entries come first in the table" {
              let mappedFlags = typedTable |> List.map (fun e -> e.Mapped)

              Expect.equal
                  mappedFlags
                  ((mappedFlags |> List.filter id) @ (mappedFlags |> List.filter not))
                  "the artefact's declared order (mapped first, then identity) has been broken"
          } ]

let private corpusArm =
    testList
        "the corpus pins it"
        [ test "enum-tokens.json is byte-identical to the table rendered from the vocabulary" {
              match IdlCertification.corpusRoot () with
              | None -> skiptest Fuaran.Tests.CorpusRoot.AbsentSkipReason
              | Some corpus ->
                  let path = Path.Combine(corpus, FileName)

                  if not (File.Exists path) then
                      failtestf
                          "%s is absent — the corpus is present but carries no enum-token table, which manifest.json points at. Regenerate with `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus <corpus>`."
                          path

                  // LF-normalised for the reason `IdlCopyTests` gives: the two
                  // repos share an eol=lf rule but need not be checked out with
                  // the same line endings, and a CRLF checkout is not drift.
                  Expect.equal
                      (File.ReadAllText(path).Replace("\r\n", "\n"))
                      (render typedTable)
                      "the corpus enum-token table has drifted from the vocabulary. It is CO-EMITTED by `--emit-corpus`, so the usual cause is a vocabulary regeneration committed without one."
          }

          test "manifest.json points at it" {
              match IdlCertification.corpusRoot () with
              | None -> skiptest Fuaran.Tests.CorpusRoot.AbsentSkipReason
              | Some corpus ->
                  use doc =
                      JsonDocument.Parse(File.ReadAllText(Path.Combine(corpus, "manifest.json")))

                  match doc.RootElement.TryGetProperty "enumTokens" with
                  | true, v ->
                      Expect.equal (v.GetString()) FileName "manifest.json's enumTokens pointer names the wrong file"
                  | false, _ ->
                      failtest
                          "manifest.json has no `enumTokens` pointer — a host that discovers artefacts through the manifest cannot reach the enum-token table, which is the whole affordance the pointer exists for"
          } ]

let private generatedArm =
    testList
        "the generated layer agrees, case by case"
        [ test "every enum type, encoder and decoder matches the table" {
              let generated = moduleType uiAssembly "Fuaran.UI.Generated"
              let mutable exercised = 0

              for entry in typedTable do
                  let ty =
                      match uiAssembly.GetType("Fuaran.UI.Generated+" + entry.Name) |> Option.ofObj with
                      | Some t -> t
                      | None ->
                          failtestf
                              "the declared enum '%s' has no generated union type — the vocabulary and the generated layer have forked"
                              entry.Name

                  Expect.equal
                      (FSharpType.GetUnionCases(ty, true)
                       |> Array.map (fun c -> c.Name)
                       |> List.ofArray)
                      (entry.Cases |> List.map fst)
                      (sprintf "%s's generated cases differ from the declared ones" entry.Name)

                  let enc =
                      match staticMethod generated ("enc" + entry.Name) with
                      | Some m -> m
                      | None -> failtestf "the generated layer has no enc%s" entry.Name

                  let dec =
                      match staticMethod generated ("dec" + entry.Name) with
                      | Some m -> m
                      | None -> failtestf "the generated layer has no dec%s" entry.Name

                  for (case, token) in entry.Cases do
                      let encoded = invoke enc [ unionCase ty case ]

                      Expect.equal
                          (jStrValue encoded)
                          (Some token)
                          (sprintf
                              "enc%s emits the wrong token for %s.%s. This is the Phase 1657 defect exactly: deriving a token from a case name compiles and produces the wrong string."
                              entry.Name
                              entry.Name
                              case)

                      match resultOk (invoke dec [ jStr token ]) with
                      | Some v ->
                          Expect.equal
                              (caseNameOf v)
                              case
                              (sprintf "dec%s maps the token %A to the wrong case" entry.Name token)
                      | None -> failtestf "dec%s refuses the declared token %A for case %s" entry.Name token case

                      // The mapped enums only: the HOST case name must not
                      // decode. A decoder that accepted both spellings would
                      // silently absorb every emitter that derived the token,
                      // which is what makes the defect invisible.
                      if entry.Mapped && case <> token then
                          Expect.isNone
                              (resultOk (invoke dec [ jStr case ]))
                              (sprintf
                                  "dec%s accepts the HOST case name %A as a wire token. The wire token is %A; accepting both spellings is how a derived-token emitter passes a round-trip and still writes bytes no other host reads."
                                  entry.Name
                                  case
                                  token)

                  exercised <- exercised + 1

              Expect.isGreaterThanOrEqual
                  exercised
                  46
                  "fewer enums were exercised than the vocabulary declared when this phase shipped — a reflective arm that finds nothing passes every assertion it makes"
          } ]

/// The hand-written policy decoders whose name is not `decode<EnumName>`.
/// Declared rather than pattern-matched, so a rename is a compile-time-visible
/// edit here rather than a silent loss of coverage.
let private policyDecoderAliases =
    Map.ofList [ "LiveRegionKind", "decodeLiveRegion" ]

/// Mapped enums with no reachable hand-written decoder function, and the
/// coverage that stands in for one.
///
/// FALSIFIABLE: each entry names a corpus fixture asserted below to still carry
/// the token, so an exemption cannot outlive the coverage it claims.
let private policyDecoderExemptions =
    [ "LinkProtection",
      "nodes/link-protected-1.json",
      "\"protection\":\"email\"",
      "decoded inline in the Link decoder rather than through a named enum decoder; the corpus round-trip fixture drives that path" ]

let private policyArm =
    testList
        "the hand-written policy decoders agree, case by case"
        [ test "every reachable decode<Enum> maps the declared tokens and refuses the host spelling" {
              let jsonDecode = moduleType opsAssembly "Fuaran.UI.Ops.JsonDecode"
              let jsonType = moduleType opsAssembly "Fuaran.UI.Ops.JsonDecode+Json"

              let jString (s: string) =
                  match
                      FSharpType.GetUnionCases(jsonType, true)
                      |> Array.tryFind (fun c -> c.Name = "JString")
                  with
                  | Some c -> FSharpValue.MakeUnion(c, [| nn s |], true) |> Unchecked.nonNull
                  | None -> failtest "Fuaran.UI.Ops.JsonDecode.Json has no JString case"

              let mutable exercised = 0

              for entry in typedTable do
                  let name =
                      policyDecoderAliases
                      |> Map.tryFind entry.Name
                      |> Option.defaultValue ("decode" + entry.Name)

                  match staticMethod jsonDecode name with
                  | None -> ()
                  | Some m ->
                      for (case, token) in entry.Cases do
                          match resultOk (invoke m [ nn "$"; jString token ]) with
                          | Some v ->
                              Expect.equal
                                  (caseNameOf v)
                                  case
                                  (sprintf "%s maps the token %A to the wrong case" name token)
                          | None -> failtestf "%s refuses the declared token %A for case %s" name token case

                          if entry.Mapped && case <> token then
                              Expect.isNone
                                  (resultOk (invoke m [ nn "$"; jString case ]))
                                  (sprintf "%s accepts the HOST case name %A where the wire token is %A" name case token)

                      exercised <- exercised + 1

              Expect.isGreaterThanOrEqual
                  exercised
                  37
                  "fewer policy decoders were exercised than existed when this phase shipped — either one was renamed (add it to policyDecoderAliases) or the reflective lookup is finding nothing"
          }

          test "every mapped enum is covered on the hand-written decode path" {
              let jsonDecode = moduleType opsAssembly "Fuaran.UI.Ops.JsonDecode"

              let exempt =
                  policyDecoderExemptions |> List.map (fun (n, _, _, _) -> n) |> Set.ofList

              let uncovered =
                  typedTable
                  |> List.filter (fun e -> e.Mapped)
                  |> List.map (fun e -> e.Name)
                  |> List.filter (fun n ->
                      not (Set.contains n exempt)
                      && (staticMethod
                              jsonDecode
                              (policyDecoderAliases |> Map.tryFind n |> Option.defaultValue ("decode" + n)))
                          .IsNone)

              Expect.isEmpty
                  uncovered
                  "a non-identity enum has no hand-written decoder the arm above can drive and no declared exemption. These six are the whole reason this suite exists; an unchecked one is the gap."
          }

          test "each declared exemption's stand-in coverage still exists" {
              match IdlCertification.corpusRoot () with
              | None -> skiptest Fuaran.Tests.CorpusRoot.AbsentSkipReason
              | Some corpus ->
                  for (name, fixture, token, why) in policyDecoderExemptions do
                      let path = Path.Combine(corpus, fixture.Replace('/', Path.DirectorySeparatorChar))

                      if not (File.Exists path) then
                          failtestf
                              "%s is exempt from the reflective decoder arm because %s — and the fixture it names, %s, is gone. Either restore it or retire the exemption; an exemption whose coverage has been deleted is worse than no exemption."
                              name
                              why
                              fixture

                      Expect.stringContains
                          (File.ReadAllText path)
                          token
                          (sprintf "the fixture standing in for %s no longer carries %s" name token)
          } ]

/// Enums whose JSON Schema definition is named something other than the enum.
let private schemaAliases = Map.ofList [ "SortDirection", "SortDir" ]

let private schemaArm =
    testList
        "the JSON Schema agrees"
        [ test "every $defs enum array matches the table" {
              use doc = JsonDocument.Parse Fuaran.UI.Ops.SchemaGen.wireFormatSchema

              let defs =
                  match doc.RootElement.TryGetProperty "$defs" with
                  | true, d -> d
                  | false, _ -> failtest "the generated schema has no $defs"

              let mutable exercised = 0

              for entry in typedTable do
                  let defName =
                      schemaAliases |> Map.tryFind entry.Name |> Option.defaultValue entry.Name

                  match defs.TryGetProperty defName with
                  | false, _ -> ()
                  | true, def ->
                      match def.TryGetProperty "enum" with
                      | false, _ -> ()
                      | true, arr ->
                          Expect.equal
                              (arr.EnumerateArray()
                               |> Seq.map (fun v -> v.GetString() |> Option.ofObj |> Option.defaultValue "<non-string>")
                               |> List.ofSeq)
                              (entry.Cases |> List.map snd)
                              (sprintf
                                  "schema $defs/%s's enum array differs from the declared wire tokens for %s. The schema is a published corpus artefact, so a divergence here is a second, wrong statement of the contract."
                                  defName
                                  entry.Name)

                          exercised <- exercised + 1

              Expect.isGreaterThanOrEqual
                  exercised
                  40
                  "fewer schema enum definitions were compared than existed when this phase shipped — either one was renamed (add it to schemaAliases) or the lookup is finding nothing"
          } ]

let private renderFidelityArm =
    testList
        "the render-fidelity token mirror agrees"
        [ test "liveRegionToken matches the declared tokens" {
              let entry =
                  typedTable
                  |> List.tryFind (fun e -> e.Name = "LiveRegionKind")
                  |> Option.defaultWith (fun () -> failtest "LiveRegionKind is not in the table")

              let ty = moduleType uiAssembly "Fuaran.UI.Generated+LiveRegionKind"

              for (case, token) in entry.Cases do
                  let v = unionCase ty case |> unbox<Fuaran.UI.Generated.LiveRegionKind>

                  Expect.equal
                      (Fuaran.UI.RenderFidelity.liveRegionToken v)
                      token
                      (sprintf
                          "RenderFidelity.liveRegionToken disagrees with the declared token for LiveRegionKind.%s. This mirror feeds the corpus's render-fidelity.json, so it is a published claim about the wire."
                          case)
          } ]

[<Tests>]
let tests =
    testList
        "Phase 1691 — the fixture-pinned enum-token table"
        [ declarationArm
          corpusArm
          generatedArm
          policyArm
          schemaArm
          renderFidelityArm ]
