namespace Fuaran.UI.OpStream.Abstractions

open System
open Fuaran.Core
open Fuaran.UI
open Fuaran.UI.Types

// ============================================================================
//  Document attestation — a signature over an emitted tree (Phase 1549).
//
//  `Attestation.fs` beside this file signs a SEGMENT of an op-stream, so a host
//  can say who wrote a run of ops. A standalone tree — the artefact a model
//  emits and a host stores, forwards, or mounts as a guest — carries no such
//  claim: it says what it contains and nothing about who produced it. This file
//  adds an optional envelope AROUND the document that binds the canonical bytes
//  of the tree to a signing key, an instant, and an open map of claims (a model
//  identity, a prompt digest, whatever the emitting host stands behind).
//
//  What that buys a host is a decision at DECODE about WHO produced a document
//  rather than only about what it contains: refuse an unsigned guest, require a
//  known key before a mount is granted any capability tag, record provenance
//  beside the op that applied the tree.
//
//  ADDITIVE, and structurally so. The envelope is outside the document, so the
//  tree's canonical bytes are untouched, every existing fixture still decodes
//  byte-identically, and an unattested document decodes exactly as before —
//  through `JsonDecode.decodeNode`, which this file CALLS and does not change.
//
//  Boundaries, stated as carefully as the property (the discipline `CRYPTO.md`
//  sets, and the same list the segment header carries because the mechanism
//  inherits its limits):
//   - It proves that the KEY HOLDER signed these canonical bytes with these
//     claims. It does not prove the claims are TRUE: `model` and `promptDigest`
//     are the signer's assertions, carried intact and bound to the bytes, and
//     nothing here checks that the named model produced the tree.
//   - It does not defend against the key holder. A compromised signer signs its
//     own forgery; the mechanism moves the question to key custody.
//   - It does not prove a USER authored anything. A key is host-held, so the
//     claim is "this host stood behind these bytes".
//   - `SignedAt` is asserted by the signer. It is bound inside the signed claim,
//     so a party who can rewrite the stored envelope cannot alter it — but the
//     SIGNER can backdate, so a revocation boundary compared against it is a
//     co-operative-failure mechanism. Whole seconds, the resolution the claim
//     payload binds, normalised through `SegmentAttestation.signedInstant`
//     exactly as the segment claim is.
//   - VERIFICATION IS A HOST OBLIGATION, never a side effect of decoding. A
//     host that decodes an attested document and reads its claims without
//     calling `decodeAttestedDocument` has read an unauthenticated assertion.
//     The specification names this so no implementation can treat it as implied.
//   - The required-or-not policy lives with the VERIFIER. A document that could
//     declare itself exempt could have that declaration written by whoever wrote
//     the rest of it.
//
//  TWO DIGESTS, over two different byte sequences, and conflating them is the
//  most consequential error available here:
//   - `DocumentDescriptor.Digest` covers the CANONICAL NODE BYTES of the tree
//     (`CanonicalJson.encodeNode`), never the transmitted envelope. A verifier
//     recomputes it by decoding the `document` member and re-encoding the
//     decoded tree, so a document transmitted in a lenient spelling (§16) that
//     canonicalises to the same tree still verifies: what was signed is the
//     tree, not its transport spelling.
//   - The SIGNING INPUT is `DocumentAttestation.claimPayload`, a separate
//     pinned-order canonical string that is never the envelope bytes.
//
//  Cross-host contract: the claim pre-image and the envelope are pinned
//  byte-for-byte by `wire-format-fixtures/attestation/document-corpus.json`
//  (WIRE_FORMAT.md §26), whose vectors were generated by an independent
//  re-implementation of the encoding.
// ============================================================================

/// What a document attestation covers: the algorithm it was signed under, and
/// the digest of the document's canonical bytes. The counterpart of
/// `SegmentDescriptor` — smaller, because a document has no range, no stream and
/// no chain anchor to bind, only its own bytes.
type DocumentDescriptor =
    {
        /// Registered algorithm id (see `AttestationAlgorithm`). Bound inside the
        /// signed claim, so a verifier dispatches on it and refuses ids it does
        /// not implement; a new primitive is a new id, never a format change.
        Algorithm: string
        /// Lower-case hex SHA-256 over the CANONICAL NODE BYTES of the document
        /// (`CanonicalJson.encodeNode`). See the two-digests note in the header.
        Digest: string
    }

module DocumentDescriptor =

    /// The claim FORMAT version, folded first into the canonical claim
    /// encoding — the same self-describing discipline as
    /// `SegmentDescriptor.descriptorVersion`, and versioned independently of the
    /// envelope's own `$attestedDocument` tag. It is bound by the signature and
    /// carried in no wire member, so a verifier folding a different version
    /// reproduces different bytes and reports an invalid signature.
    [<Literal>]
    let documentVersion = 1

    /// The digest of an already-canonical document encoding.
    let digestOfCanonical (canonicalJson: string) : string = Hashing.sha256Hex canonicalJson

    /// Describe a tree: canonical-encode it and digest those bytes.
    let ofTree (algorithm: string) (tree: Node<'Msg>) : DocumentDescriptor =
        { Algorithm = algorithm
          Digest = digestOfCanonical (CanonicalJson.encodeNode tree) }

    /// The claims map as canonical JSON: Ordinal member order and the §2 rule-6
    /// escaping, through the substrate's own canonical renderer rather than a
    /// second hand-rolled one. Used identically by the signing pre-image and by
    /// the envelope, so the two can never disagree about a claim's bytes.
    let internal claimsJson (claims: Map<string, string>) : string =
        Canon.render (JObj(claims |> Map.toList |> List.map (fun (k, v) -> k, JStr v)))

    /// The pinned field body shared by the claim payload and this descriptor's
    /// own encoding. Field order — documentVersion / algorithm / digest — is a
    /// cross-host contract; `attestation/document-corpus.json` pins the bytes.
    let internal fields (d: DocumentDescriptor) : string =
        "\"documentVersion\":"
        + string documentVersion
        + ",\"algorithm\":"
        + SegmentDescriptor.jstr d.Algorithm
        + ",\"digest\":"
        + SegmentDescriptor.jstr d.Digest

    /// The canonical encoding of a descriptor on its own — deterministic bytes,
    /// pinned field order, the same hand-built canonical-JSON discipline the
    /// segment descriptor uses.
    let encode (d: DocumentDescriptor) : string = "{" + fields d + "}"

/// A signature over a document claim. `Signature` covers the canonical CLAIM
/// payload (`DocumentAttestation.claimPayload`), which binds the descriptor PLUS
/// `KeyId`, `SignedAt` and `Claims` — so a party who can rewrite the stored
/// envelope can alter none of them without invalidating the signature. That
/// `Claims` is inside the signature is what makes a model identity a claim
/// rather than an annotation.
type DocumentAttestation =
    {
        Descriptor: DocumentDescriptor
        /// Names the signing key in the VERIFIER's key directory. It is not a
        /// key and it is not a trust root.
        KeyId: string
        /// Asserted by the SIGNER — see the boundary note in the file header.
        /// Whole seconds, the resolution the claim payload binds and therefore
        /// the resolution the signature covers.
        SignedAt: DateTimeOffset
        /// The open claim set. This format reserves no key and interprets none:
        /// `model` and `promptDigest` are conventions, not vocabulary.
        Claims: Map<string, string>
        /// Signature bytes in the algorithm id's declared encoding
        /// (base64 IEEE P1363 `r||s` for `ecdsa-p256-sha256-v1`).
        Signature: string
    }

module DocumentAttestation =

    /// The instant a signature actually covers: `signedAt` floored to whole
    /// seconds, the resolution `claimPayload` binds. The same normalisation the
    /// segment claim uses, and deliberately the same function — signers call it
    /// before binding AND before storing, verifiers call it on a stored
    /// attestation, so a sub-second edit can move no verdict.
    let signedInstant (signedAt: DateTimeOffset) : DateTimeOffset =
        SegmentAttestation.signedInstant signedAt

    /// The exact string whose UTF-8 bytes the signature covers. Pinned field
    /// order: the descriptor fields, then keyId / signedAt / claims. Never the
    /// envelope bytes — see the two-digests note in the file header.
    let claimPayload
        (d: DocumentDescriptor)
        (keyId: string)
        (signedAt: DateTimeOffset)
        (claims: Map<string, string>)
        : string =
        "{"
        + DocumentDescriptor.fields d
        + ",\"keyId\":"
        + SegmentDescriptor.jstr keyId
        + ",\"signedAt\":"
        + string (signedAt.ToUnixTimeSeconds())
        + ",\"claims\":"
        + DocumentDescriptor.claimsJson claims
        + "}"

    /// The claim payload an existing attestation asserts.
    let claimPayloadOf (a: DocumentAttestation) : string =
        claimPayload a.Descriptor a.KeyId a.SignedAt a.Claims

/// The crypto half of document verification: does `signature` verify over
/// `claimPayload` under `key`? A separate seam from `IAttestationVerifier`
/// because that one is typed to a `SegmentAttestation` and a document has no
/// range, stream or chain anchor to put in one; forcing a document into that
/// shape would mean signing fields that mean nothing.
///
/// Implementations dispatch on the key's algorithm id and answer `false` for
/// ids they do not implement. Everything ABOVE the crypto — key resolution,
/// revocation, the digest comparison — lives in `decodeAttestedDocument`, which
/// returns a typed refusal rather than a boolean precisely because "the
/// signature is wrong", "the key is unknown" and "the document is not the one
/// signed" demand different responses from a consumer.
type IClaimSignatureVerifier =
    abstract member VerifyClaim: claimPayload: string -> signature: string -> key: KeyDirectoryEntry -> Async<bool>

/// Why an attested-document decode did not produce a verified document. A typed
/// DU rather than a boolean, and rather than one error code, because the
/// remedies differ: `NotAttested` means fall back to the ordinary decode,
/// `UnknownKey` means establish the key out of band, `DigestMismatch` means the
/// document shown is not the document signed.
[<RequireQualifiedAccess>]
type DocumentRefusal =
    /// The input is a well-formed JSON object carrying no `$attestedDocument`
    /// tag — an ordinary, honestly unattested document. A host that wants the
    /// tree regardless calls `JsonDecode.decodeNode` on the same input; a host
    /// asking an evidence question treats this as a refusal.
    | NotAttested
    /// The envelope carries the tag and is structurally wrong: not JSON, not an
    /// object, a missing or mistyped member, or an undeclared one (default-deny
    /// by shape — a member a verifier silently skips is a member an adversary
    /// can add).
    | InvalidEnvelope of Fuaran.UI.Ops.JsonDecode.DecodeError
    /// The envelope declares a format version this decoder does not implement.
    | UnsupportedFormat of found: string
    /// The verifier's key directory does not know the key id. Deliberately
    /// distinct from `SignatureInvalid`: the remedy is establishing the key out
    /// of band, not distrusting the document.
    | UnknownKey of keyId: string
    /// The signature does not verify over the canonical claim payload under the
    /// named key — or the attestation is void (signed at or after the key's
    /// revocation boundary, or under a key of a different algorithm).
    | SignatureInvalid of keyId: string
    /// The `document` member failed the standard wire decode.
    | DocumentDecode of Fuaran.UI.Ops.JsonDecode.DecodeError
    /// The claim is authentic and covers different bytes: the document decoded
    /// cleanly, and the digest of its canonical form is not the signed digest.
    /// This is the verdict an edited document produces.
    | DigestMismatch of claimed: string * actual: string

/// A document whose claim verified end-to-end: the signature is authentic under
/// a directory-resolved key, and the digest of the decoded tree's canonical form
/// is the signed digest. `Tree` is the storage-erased wire shape (`Node<obj>`,
/// closures inert by design), exactly as the ordinary decode produces.
type AttestedDocument =
    {
        Tree: Node<obj>
        Attestation: DocumentAttestation
        /// Non-fatal findings — an advisory expiry that predates `SignedAt`, a
        /// validity start that postdates it, a key revoked after signing. A
        /// consumer that treats any warning as fatal is choosing a stricter policy
        /// than the mechanism imposes, which is its right.
        Warnings: EvidenceWarning list
    }

/// The envelope codec: encode a tree plus its attestation as one wire document,
/// and decode one back with its claim verified or a typed refusal.
module DocumentEnvelope =

    module JsonDecode = Fuaran.UI.Ops.JsonDecode

    /// The self-identifying format tag. The envelope's own version, versioned
    /// independently of `DocumentDescriptor.documentVersion` (the claim shape).
    [<Literal>]
    let FormatKey = "$attestedDocument"

    /// The envelope version this codec produces and accepts.
    [<Literal>]
    let FormatVersion = "1"

    // ── local decode helpers (the shape every envelope codec here uses) ──────

    let private err (code: string) (path: string) (message: string) : JsonDecode.DecodeError =
        { Code = code
          Path = path
          Message = message
          ExpectedShape = None }

    /// Re-root an inner decode error under `prefix` (a tree decode error at
    /// `$.kind` surfaces at `$.document.kind`).
    let private rePath (prefix: string) (e: JsonDecode.DecodeError) : JsonDecode.DecodeError =
        let inner = e.Path

        let rerooted =
            if inner = "$" then prefix
            elif inner.StartsWith "$" then prefix + inner.Substring 1
            else prefix + "." + inner

        { e with Path = rerooted }

    let private fieldOpt (name: string) (fields: (string * JVal) list) : JVal option =
        fields |> List.tryPick (fun (k, v) -> if k = name then Some v else None)

    /// First key of `fields` (document order) not in `allowed` — the
    /// default-deny-by-shape probe every object position runs (§18.3).
    let private firstUndeclared (allowed: string list) (fields: (string * JVal) list) : string option =
        fields
        |> List.tryPick (fun (k, _) -> if List.contains k allowed then None else Some k)

    let private requireStr
        (path: string)
        (name: string)
        (fields: (string * JVal) list)
        : Result<string, JsonDecode.DecodeError> =
        match fieldOpt name fields with
        | None -> Error(err "MISSING_FIELD" path (sprintf "missing required field '%s'" name))
        | Some(JStr s) when s <> "" -> Ok s
        | Some(JStr _) -> Error(err "WRONG_TYPE" path (sprintf "'%s' must be a non-empty string" name))
        | Some _ -> Error(err "WRONG_TYPE" path (sprintf "'%s' must be a string" name))

    // ── encode ──────────────────────────────────────────────────────────────

    /// The attestation object's own wire form: the six members, Ordinal-ordered
    /// per §2 rule 4. Hand-built rather than rendered from a `JVal` because
    /// `signedAt` is a unix-second int64 and the wire number model carries
    /// `int`; the members are a closed set, so the order is stated once here and
    /// pinned by the corpus.
    let private encodeAttestation (a: DocumentAttestation) : string =
        "{\"algorithm\":"
        + SegmentDescriptor.jstr a.Descriptor.Algorithm
        + ",\"claims\":"
        + DocumentDescriptor.claimsJson a.Claims
        + ",\"digest\":"
        + SegmentDescriptor.jstr a.Descriptor.Digest
        + ",\"keyId\":"
        + SegmentDescriptor.jstr a.KeyId
        + ",\"signature\":"
        + SegmentDescriptor.jstr a.Signature
        + ",\"signedAt\":"
        + string (a.SignedAt.ToUnixTimeSeconds())
        + "}"

    /// Encode an attested document. The `document` member is the tree's ordinary
    /// canonical encoding, spliced verbatim — the same bytes the digest covers,
    /// so an encoder cannot produce an envelope whose digest is of something
    /// other than what it shipped.
    let encode (attestation: DocumentAttestation) (tree: Node<'Msg>) : string =
        "{\""
        + FormatKey
        + "\":\""
        + FormatVersion
        + "\",\"attestation\":"
        + encodeAttestation attestation
        + ",\"document\":"
        + CanonicalJson.encodeNode tree
        + "}"

    /// Attest a tree through `Fuaran.Core`'s synchronous `IAttestationSink` (the
    /// Phase-320 seam) — the same adaptation `AttestationSigner.ofCoreSink`
    /// makes for segments, and for the same reason: Core's seam signs an opaque
    /// string, so passing the canonical claim payload needs no Core change at
    /// all, and no key crosses this surface.
    ///
    /// The caller names the key id the sink signs under; if the sink's returned
    /// attestation names a DIFFERENT key the result is discarded rather than
    /// recorded under a claim the signature does not cover. `now` is
    /// host-supplied, and is normalised to the resolution the payload binds, so
    /// the stored `SignedAt` IS the value the signature covers.
    let attest
        (now: unit -> DateTimeOffset)
        (algorithm: string)
        (keyId: string)
        (claims: Map<string, string>)
        (sink: Fuaran.Core.IAttestationSink)
        (tree: Node<'Msg>)
        : DocumentAttestation option =
        let descriptor = DocumentDescriptor.ofTree algorithm tree
        let signedAt = DocumentAttestation.signedInstant (now ())
        let payload = DocumentAttestation.claimPayload descriptor keyId signedAt claims

        match sink.Sign payload with
        | Some signed when signed.KeyId = keyId ->
            Some
                { Descriptor = descriptor
                  KeyId = keyId
                  SignedAt = signedAt
                  Claims = claims
                  Signature = signed.Signature }
        | _ -> None

    // ── decode ──────────────────────────────────────────────────────────────

    let private decodeClaims (path: string) (v: JVal) : Result<Map<string, string>, JsonDecode.DecodeError> =
        match v with
        | JObj members ->
            let rec go acc rest =
                match rest with
                | [] -> Ok(Map.ofList (List.rev acc))
                | (k, JStr s) :: tail -> go ((k, s) :: acc) tail
                | (k, _) :: _ ->
                    Error(err "WRONG_TYPE" (path + "." + k) (sprintf "claim '%s' must be a string value" k))

            go [] members
        | _ -> Error(err "WRONG_TYPE" path "'claims' must be an object")

    /// `signedAt` is a whole number of unix seconds. Read through the wire's
    /// blessed numeric accessor rather than by matching `JInt`: JSON has one
    /// number type, and a timestamp beyond `Int32` (every instant after 2038)
    /// arrives as the float case. A fractional value is refused — whole seconds
    /// is the resolution the claim binds, so a sub-second spelling is a claim
    /// this format cannot represent, not one to round.
    let private decodeSignedAt (path: string) (v: JVal) : Result<DateTimeOffset, JsonDecode.DecodeError> =
        match JVal.asFloat v with
        | Some f when
            not (Double.IsNaN f)
            && not (Double.IsInfinity f)
            && f = floor f
            && abs f <= 9.007199254740992e15
            ->
            Ok(DateTimeOffset.FromUnixTimeSeconds(int64 f))
        | Some _ -> Error(err "WRONG_TYPE" path "'signedAt' must be a whole number of unix seconds")
        | None -> Error(err "WRONG_TYPE" path "'signedAt' must be a number")

    let private decodeAttestation (fields: (string * JVal) list) : Result<DocumentAttestation, JsonDecode.DecodeError> =
        match firstUndeclared [ "algorithm"; "claims"; "digest"; "keyId"; "signature"; "signedAt" ] fields with
        | Some stray ->
            Error(
                err
                    "UNDECLARED_FIELD"
                    ("$.attestation." + stray)
                    (sprintf "undeclared key '%s' on the attestation" stray)
            )
        | None ->
            requireStr "$.attestation.algorithm" "algorithm" fields
            |> Result.bind (fun algorithm ->
                requireStr "$.attestation.digest" "digest" fields
                |> Result.bind (fun digest ->
                    requireStr "$.attestation.keyId" "keyId" fields
                    |> Result.bind (fun keyId ->
                        requireStr "$.attestation.signature" "signature" fields
                        |> Result.bind (fun signature ->
                            (match fieldOpt "signedAt" fields with
                             | None ->
                                 Error(
                                     err
                                         "MISSING_FIELD"
                                         "$.attestation.signedAt"
                                         "missing required field 'signedAt'"
                                 )
                             | Some v -> decodeSignedAt "$.attestation.signedAt" v)
                            |> Result.bind (fun signedAt ->
                                (match fieldOpt "claims" fields with
                                 | None ->
                                     Error(
                                         err
                                             "MISSING_FIELD"
                                             "$.attestation.claims"
                                             "missing required field 'claims'"
                                     )
                                 | Some v -> decodeClaims "$.attestation.claims" v)
                                |> Result.map (fun claims ->
                                    { Descriptor =
                                        ({ Algorithm = algorithm
                                           Digest = digest }
                                        : DocumentDescriptor)
                                      KeyId = keyId
                                      SignedAt = signedAt
                                      Claims = claims
                                      Signature = signature }))))))

    /// Decode an attested document and verify its claim, offline: nothing beyond
    /// the envelope and the verifier's OWN key directory. A key travelling
    /// inside or beside the envelope is never a trust root — a party who mints a
    /// key pair and publishes the public half has produced a document that
    /// agrees with itself.
    ///
    /// Order mirrors `Evidence.verify`: authenticate the claim first (key
    /// resolution, algorithm dispatch, revocation, signature), THEN prove the
    /// document IS the one signed (decode, re-encode canonically, compare the
    /// digest). So an unauthenticated envelope never gets as far as decoding an
    /// untrusted tree.
    let decodeAttestedDocument
        (directory: IKeyDirectory)
        (verifier: IClaimSignatureVerifier)
        (json: string)
        : Async<Result<AttestedDocument, DocumentRefusal>> =
        async {
            match Json.parse json with
            | Error m ->
                return Error(DocumentRefusal.InvalidEnvelope(err "INVALID_JSON" "$" ("input is not valid JSON: " + m)))
            | Ok(JObj fields) ->
                // The format tag first, and its ABSENCE is its own answer: an
                // ordinary document is honestly unattested, not malformed.
                let tag =
                    match fieldOpt FormatKey fields with
                    | None -> Error DocumentRefusal.NotAttested
                    | Some(JStr v) when v = FormatVersion -> Ok()
                    | Some(JStr v) -> Error(DocumentRefusal.UnsupportedFormat v)
                    | Some _ ->
                        Error(
                            DocumentRefusal.InvalidEnvelope(
                                err "WRONG_TYPE" ("$." + FormatKey) (sprintf "'%s' must be a string" FormatKey)
                            )
                        )

                match tag with
                | Error refusal -> return Error refusal
                | Ok() ->
                    match firstUndeclared [ FormatKey; "attestation"; "document" ] fields with
                    | Some stray ->
                        return
                            Error(
                                DocumentRefusal.InvalidEnvelope(
                                    err
                                        "UNDECLARED_FIELD"
                                        ("$." + stray)
                                        (sprintf "undeclared key '%s' on the attested-document envelope" stray)
                                )
                            )
                    | None ->
                        let attestationResult =
                            match fieldOpt "attestation" fields with
                            | None -> Error(err "MISSING_FIELD" "$.attestation" "missing required field 'attestation'")
                            | Some(JObj members) -> decodeAttestation members
                            | Some _ -> Error(err "WRONG_TYPE" "$.attestation" "'attestation' must be an object")

                        match attestationResult with
                        | Error e -> return Error(DocumentRefusal.InvalidEnvelope e)
                        | Ok attestation ->
                            match fieldOpt "document" fields with
                            | None ->
                                return
                                    Error(
                                        DocumentRefusal.InvalidEnvelope(
                                            err "MISSING_FIELD" "$.document" "missing required field 'document'"
                                        )
                                    )
                            | Some documentJv ->
                                let! resolved = directory.ResolveKey attestation.KeyId

                                match resolved with
                                | None -> return Error(DocumentRefusal.UnknownKey attestation.KeyId)
                                | Some key when key.Algorithm <> attestation.Descriptor.Algorithm ->
                                    // A signature cannot be valid under a key of
                                    // a different algorithm; calling it invalid
                                    // rather than unknown keeps `UnknownKey`'s
                                    // remedy honest.
                                    return Error(DocumentRefusal.SignatureInvalid attestation.KeyId)
                                | Some key ->
                                    let payload = DocumentAttestation.claimPayloadOf attestation
                                    let! signatureOk = verifier.VerifyClaim payload attestation.Signature key

                                    // The instant the SIGNATURE covers, not the
                                    // raw stored field: a sub-second edit can
                                    // move no attestation across a boundary.
                                    let signedAt = DocumentAttestation.signedInstant attestation.SignedAt

                                    let signedAtOrAfterRevocation =
                                        match key.RevokedFrom with
                                        | Some boundary -> signedAt >= boundary
                                        | None -> false

                                    if not signatureOk || signedAtOrAfterRevocation then
                                        return Error(DocumentRefusal.SignatureInvalid attestation.KeyId)
                                    else
                                        match JsonDecode.decodeNodeObj (Canon.render documentJv) with
                                        | Error e -> return Error(DocumentRefusal.DocumentDecode(rePath "$.document" e))
                                        | Ok tree ->
                                            let actual =
                                                DocumentDescriptor.digestOfCanonical (CanonicalJson.encodeNode tree)

                                            if actual <> attestation.Descriptor.Digest then
                                                return
                                                    Error(
                                                        DocumentRefusal.DigestMismatch(
                                                            attestation.Descriptor.Digest,
                                                            actual
                                                        )
                                                    )
                                            else
                                                let warnings =
                                                    [ match key.Expires with
                                                      | Some expiry when signedAt > expiry ->
                                                          EvidenceWarning.KeyExpired key.KeyId
                                                      | _ -> ()
                                                      match key.NotBefore with
                                                      | Some notBefore when signedAt < notBefore ->
                                                          EvidenceWarning.KeySignedBeforeValidity key.KeyId
                                                      | _ -> ()
                                                      match key.RevokedFrom with
                                                      | Some _ -> EvidenceWarning.KeyRevokedAfterSigning key.KeyId
                                                      | None -> () ]

                                                return
                                                    Ok
                                                        { Tree = tree
                                                          Attestation = attestation
                                                          Warnings = warnings }
            | Ok _ ->
                return
                    Error(
                        DocumentRefusal.InvalidEnvelope(
                            err "WRONG_TYPE" "$" "an attested document must be a JSON object"
                        )
                    )
        }

    /// The capability tags a `Mount` may be granted, given the attestation
    /// outcome of the document that carried it.
    ///
    /// `MountSpec.Capabilities` is a REQUEST, not a grant: it arrives on the
    /// wire, so a decoded tree names whatever tags it likes. A host that admits
    /// guests from elsewhere can make a verified claim the precondition of
    /// granting any of them, and `admit` is where it says WHICH verified keys it
    /// trusts for that purpose — a valid signature by a stranger is still a
    /// stranger. Default-deny by construction: every refusal, and every verified
    /// document the host declines to admit, grants the empty list.
    ///
    /// This is a host-side narrowing on the footing of the kind-admission policy
    /// (`KindPolicy`): it narrows no wire, and a document refused a capability is
    /// still a valid document.
    let grantedCapabilities
        (admit: AttestedDocument -> bool)
        (outcome: Result<AttestedDocument, DocumentRefusal>)
        (declared: string list)
        : string list =
        match outcome with
        | Ok document when admit document -> declared
        | _ -> []
