module Fuaran.UI.JsonDecode.Tests.FuzzEvidence

// ============================================================================
//  Phase 779 — the published totality evidence.
//
//  `docs/DECODER-ROBUSTNESS.md` is GENERATED by the long fuzz run, in whole and
//  not in part. That is the point of the file existing at all: a hand-written
//  note claiming "N inputs, zero escapes" is a claim about what someone
//  remembered to update, and the documents that cite it inherit exactly that
//  much confidence. Generating it means the numbers in the note cannot be older
//  than the run that produced them, and cannot be edited into agreement with a
//  decoder that no longer behaves that way.
//
//  PUBLIC-SURFACE CLEAN. Everything this module emits ships in an OSS repo, so
//  the text names only the public package surface, the wire format and the
//  conformance corpus. It names no unpublished project, product or process.
// ============================================================================

open System
open System.Globalization
open System.IO
open System.Text

/// Walk up from the test binary for the repo root — the directory holding the
/// solution file.
let repoRoot () : string option =
    let rec climb (dir: DirectoryInfo | null) : string option =
        match dir with
        | null -> None
        | d ->
            if File.Exists(Path.Combine(d.FullName, "Fuaran.sln")) then
                Some d.FullName
            else
                climb d.Parent

    climb (DirectoryInfo(AppContext.BaseDirectory))

let private mib (bytes: int64) : string =
    (float bytes / 1024.0 / 1024.0).ToString("F1", CultureInfo.InvariantCulture)

let private thousands (n: int) : string =
    n.ToString("N0", CultureInfo.InvariantCulture)

/// Render the note. Split from the writing so a caller can inspect it, and so
/// the shape is testable without touching the repo.
let render (stats: DecoderFuzz.RunStats) (cfg: DecoderFuzz.Config) (budgets: DecoderFuzz.Budgets) : string =
    let sb = StringBuilder()
    let line (s: string) = sb.Append(s).Append('\n') |> ignore

    let rejectRows =
        stats.RejectCodes
        |> Map.toList
        |> List.sortByDescending snd
        |> List.map (fun (code, n) -> sprintf "| `%s` | %s |" code (thousands n))

    line "# Decoder robustness: totality evidence"
    line ""
    line "> **This file is generated.** It is rewritten in full by the long fuzz run:"
    line ">"
    line "> ```"
    line "> dotnet run --project src/Fuaran.UI.JsonDecode.Tests -c Release -- --fuzz-long <iterations> [seed]"
    line "> ```"
    line ">"
    line "> Do not hand-edit it. The numbers below are only worth citing because"
    line "> nothing can put them out of step with the run that produced them."
    line ""
    line "## The claim under test"
    line ""
    line "Decoding is **total**: a malformed or hostile input yields a structured,"
    line "typed error, never an exception and never a hang. That claim is what makes"
    line "it safe to point the decoder at bytes from an untrusted producer — a"
    line "language model's emission, a third-party service, a stored document of"
    line "unknown provenance — and it is the claim this harness exists to falsify."
    line ""
    line "It was previously supported by a **curated** reject corpus: inputs an"
    line "author chose. That is evidence about the author's imagination. The harness"
    line "described here generates inputs nobody chose."
    line ""
    line "## Methodology"
    line ""
    line "Each generated input is fed to **both** public decode entry points"
    line "(`JsonDecode.decodeNodeObj` and `JsonDecode.decodeOp`) and judged against"
    line "four invariants:"
    line ""
    line "1. **Totality** — the call returns `Ok tree` or a typed `DecodeError`."
    line "   Any escaping exception is a counterexample."
    line "2. **Termination** — it returns inside a time budget. A soft breach is"
    line "   recorded as a counterexample; a hard breach is a genuine hang, and a"
    line "   watchdog terminates the process with a diagnosis rather than leaving a"
    line "   job to time out with nothing to show."
    line "3. **Bounded work** — allocation stays inside a budget proportional to the"
    line "   input, which is what makes adversarial nesting and width visible as"
    line "   *super-linear* blow-up rather than as a slow test."
    line "4. **Fixed point** — an accepted input's canonical form re-decodes, and"
    line "   re-encodes to itself. `encode(decode(encode x)) = encode x`, fuzzed"
    line "   over the reachable accept-space rather than pinned by fixtures."
    line ""
    line "Inputs come from five families, mixed per iteration:"
    line ""
    line "- **Corpus-seeded mutation** — every payload in the conformance corpus's"
    line "  node, op, reject and lenient families, corrupted by one to four stacked"
    line "  mutators (character flips, span deletion and duplication, truncation,"
    line "  transposition, structural-character repetition, value retyping,"
    line "  key deletion and duplication, escape injection, junk prefixes and"
    line "  suffixes). Reject fixtures are the most productive seeds available:"
    line "  they already sit one edit from the refusal boundary."
    line "- **Near-miss vocabulary** — discriminator values one edit away from a"
    line "  real kind name (case changes, pluralisation, a dropped or inserted"
    line "  character). This is the class a real emitter produces and the class a"
    line "  curated corpus covers worst, because a human writing fixtures reaches"
    line "  for obvious garbage."
    line "- **Structure-aware generation** — random documents assembled from the"
    line "  real wire key vocabulary, so a generated near-miss reaches into the"
    line "  typed decoders instead of bouncing off the first missing field."
    line "- **Crossover** — the prefix of one corpus payload spliced to the suffix"
    line "  of another, producing half-valid documents no single-seed mutation"
    line "  reaches."
    line "- **Pathological payloads** — nesting, width and string length taken past"
    line "  the declared resource limits, assembled as text (building one as a"
    line "  value would overflow while constructing the input and prove nothing)."
    line ""
    line "Generation is driven by a self-contained SplitMix64 generator rather than"
    line "the platform PRNG, whose sequence is documented as implementation-defined."
    line "Given a seed and a configuration, iteration *N* is byte-identical on every"
    line "machine, so a find is replayable from the seed alone — which matters most"
    line "for the one failure mode that cannot persist anything on its way out."
    line ""
    line "Any counterexample is **minimised** by delta-debugging (span deletion"
    line "while the failure class holds) and persisted with its seed, iteration and"
    line "generating mutator chain."
    line ""
    line "### What this does not cover"
    line ""
    line "- A `StackOverflowException` cannot be caught on this runtime: the process"
    line "  is torn down without unwinding. That is a stated boundary, not a gap —"
    line "  the process dying is itself the red signal, and the deterministic seed"
    line "  reproduces the input that did it. The resource limits exist so this path"
    line "  is not reachable from a bounded payload."
    line "- Allocation is measured per thread, so the budget detects amplification,"
    line "  not steady-state footprint."
    line "- This is a decode-side result for THIS host only. The wire format has"
    line "  several independent reference implementations, each with its own"
    line "  hand-written decoder, and none of them is covered by the figures below"
    line "  (see the follow-up section at the end)."
    line ""
    line "### Go-red proof"
    line ""
    line "A harness nobody has seen fail is decoration, and decoration passes. The"
    line "invariant machinery is therefore parameterised over the decoder under"
    line "test, and the suite runs it against five deliberately-broken stand-ins —"
    line "one throwing, one slow, one over-allocating, one whose canonical form is"
    line "not a fixed point, one whose canonical form it cannot re-read — asserting"
    line "each is caught and classified correctly. A sixth, inverse assertion checks"
    line "the unmutated decoder is clean over the same inputs, so the proof shows"
    line "discrimination rather than indiscriminate alarm."
    line ""
    line "## Latest long run"
    line ""
    line (sprintf "| | |")
    line (sprintf "|---|---|")

    line (
        sprintf "| Run at | %s |" (DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss 'UTC'", CultureInfo.InvariantCulture))
    )

    line (sprintf "| Seed | `%d` |" stats.Seed)
    line (sprintf "| Iterations | %s |" (thousands stats.Iterations))
    line (sprintf "| Inputs decoded | %s (each iteration feeds both entry points) |" (thousands stats.Inputs))
    line (sprintf "| Corpus payloads used as seeds | %s |" (thousands stats.SeedCount))
    line (sprintf "| Max generated payload | %s chars |" (thousands cfg.MaxPayloadChars))
    line (sprintf "| Wall clock | %s s |" (stats.ElapsedSeconds.ToString("F1", CultureInfo.InvariantCulture)))
    line (sprintf "| **Escapes, hangs, budget breaches** | **%d** |" (List.length stats.Counterexamples))
    line ""
    line "Outcome distribution:"
    line ""
    line "| Outcome | Count |"
    line "|---|---|"
    line (sprintf "| accepted (canonical form is a fixed point) | %s |" (thousands stats.Accepted))

    for row in rejectRows do
        line row

    line ""
    line "Observed maxima, and the budgets they are measured against:"
    line ""
    line "| | Observed | Budget |"
    line "|---|---|---|"

    line (
        sprintf
            "| Slowest single decode | %s ms | %s ms soft, %s ms hard |"
            (stats.MaxDecodeMs.ToString("F0", CultureInfo.InvariantCulture))
            (budgets.SoftTimeMs.ToString("F0", CultureInfo.InvariantCulture))
            (budgets.HardTimeMs.ToString("F0", CultureInfo.InvariantCulture))
    )

    line (
        sprintf
            "| Largest allocation, ordinary input (%s inputs) | %s MiB; peak amplification %s x | %s MiB floor, then %d bytes per input char |"
            (thousands stats.OrdinaryInputs)
            (mib stats.MaxOrdinaryAllocBytes)
            (stats.MaxOrdinaryAllocRatio.ToString("N0", CultureInfo.InvariantCulture))
            (mib budgets.AllocFloorBytes)
            budgets.AllocPerChar
    )

    line (
        sprintf
            "| Largest allocation, over-closed input (%s inputs) | %s MiB; peak amplification %s x | %s MiB |"
            (thousands stats.OverClosedInputs)
            (mib stats.MaxOverCloseAllocBytes)
            (stats.MaxOverCloseAllocRatio.ToString("N0", CultureInfo.InvariantCulture))
            (mib budgets.OverCloseFloorBytes)
    )

    line ""
    line "In each allocation row the byte maximum and the amplification maximum are"
    line "**independent** maxima over the run, not two readings of one input: the"
    line "largest absolute allocation comes from a large payload, the largest"
    line "amplification from a small one. Dividing one by the other would be"
    line "meaningless."
    line ""

    if List.isEmpty stats.Counterexamples then
        line "No input escaped the refusal contract: every one of the inputs above"
        line "returned either a decoded tree whose canonical form is a fixed point, or"
        line "a typed error, inside both budgets."
    else
        line "**Counterexamples found in this run** (each is a defect to fix in the"
        line "decoder and to land as a permanent reject fixture in the shared corpus,"
        line "so every conformant host inherits the case):"
        line ""

        for c in stats.Counterexamples do
            line (
                sprintf
                    "- `%s` iteration %d, origin `%s` — %s"
                    c.Subject
                    c.Iteration
                    c.Origin
                    (DecoderFuzz.describeVerdict c.Verdict)
            )

    line ""
    line "## Open finding: the over-closed recovery path is super-linear"
    line ""
    line "The two allocation rows above are reported separately because they measure"
    line "genuinely different things, and blending them would hide the second."
    line ""
    line "A document with a surplus structural closer engages a recovery gate that"
    line "enumerates candidate repairs and re-parses the document for each. The cost"
    line "is quadratic in document length. Measured on a node list with one surplus"
    line "closer placed mid-document, every row **decoding successfully** — this is"
    line "the cost of the accept path, not of a refusal:"
    line ""
    line "| input chars | allocated | ms |"
    line "|---|---|---|"
    line "| 899 | 0.5 MiB | 0.5 |"
    line "| 2,129 | 2.3 MiB | 2.8 |"
    line "| 4,179 | 8.1 MiB | 8.6 |"
    line "| 8,280 | 30.1 MiB | 22.3 |"
    line "| 16,580 | 115.9 MiB | 81.9 |"
    line ""
    line "Doubling the input roughly quadruples both figures. Growth stops beyond"
    line "that only because the gate refuses outright past its closer-count bound — a"
    line "cliff, not a taper. So the work is **bounded** and the totality claim above"
    line "is unaffected: no escape, no hang, a typed outcome either way. What a"
    line "producer of untrusted input controls is the amplification: about"
    line "seven thousand fold at the bottom of the ladder above, and the over-closed"
    line "peak measured by the run itself is in the table. A well-formed document of"
    line "the same size costs 40 to 60 bytes per character."
    line ""
    line "**No fixture in the curated corpus reaches this**, which is the point: the"
    line "heaviest payload across every corpus family decodes at 63 bytes per"
    line "character. The property was reachable, unrecorded, and invisible to the"
    line "evidence that existed before this harness."
    line ""
    line "It is deliberately **not fixed here**. The remedy is either a lower"
    line "enumeration bound, which changes *which* malformed documents recover and is"
    line "measured against a labelled acceptance oracle, or a restructured"
    line "enumeration that shares parse work across candidates. Both are decisions"
    line "about how far the recovery feature should reach, and neither is something a"
    line "fuzz harness should settle as a side effect of finding it. The cost is"
    line "pinned by a regression test at 8 KB so it cannot silently grow, and"
    line "reported in every run so it cannot silently return to being unrecorded."
    line ""
    line "## Follow-up: the other host decode paths"
    line ""
    line "The result above is evidence about one decoder. The wire format is"
    line "implemented independently in several languages, and a totality claim made"
    line "for the format rather than for a host is only as good as its weakest"
    line "decoder — so each of these is a distinct piece of work, not a port:"
    line ""
    line "- **TypeScript** — the same invariants, with the language's own failure"
    line "  modes: an exception is the default control flow, so \"returns a typed"
    line "  error\" needs asserting rather than assuming, and prototype-pollution"
    line "  keys (`__proto__`, `constructor`) are a live class this host does not"
    line "  have. The harness already generates them."
    line "- **Python** — recursion limits make the depth family behave differently:"
    line "  the interpreter raises rather than terminating the process, so a deep"
    line "  payload is catchable there and the guard has a different shape."
    line "- **Go** — no exceptions, so the totality invariant is about panics and"
    line "  about error returns being complete; the time and allocation budgets"
    line "  transfer directly."
    line "- **Rust** — the sum-typed decoders make several of the classes above"
    line "  unrepresentable, which is worth demonstrating rather than asserting;"
    line "  the interesting residue is the allocation budget and the recovery paths."
    line ""
    line "A cross-host leg would also gain something none of the single-host runs"
    line "can: the same generated input judged by every decoder, so a DIVERGENCE in"
    line "what is accepted becomes visible. That is a conformance property, not a"
    line "robustness one, and it is the natural next step once the harness shape"
    line "here is settled."
    line ""
    line "## Reproducing this"
    line ""
    line "```"

    line (
        sprintf
            "dotnet run --project src/Fuaran.UI.JsonDecode.Tests -c Release -- --fuzz-long %d %d"
            stats.Iterations
            stats.Seed
    )

    line "```"
    line ""
    line "A bounded run of the same harness is part of the repository test gate, so a"
    line "decoder change that reintroduces an escape is caught by the next test run"
    line "rather than by the next long run somebody remembers to launch."
    sb.ToString()

/// Write the note to `docs/DECODER-ROBUSTNESS.md`. Returns the path written, or
/// `None` when the repo root cannot be located (a stray binary somewhere else).
let write (stats: DecoderFuzz.RunStats) (cfg: DecoderFuzz.Config) (budgets: DecoderFuzz.Budgets) : string option =
    match repoRoot () with
    | None -> None
    | Some root ->
        let dir = Path.Combine(root, "docs")
        Directory.CreateDirectory dir |> ignore
        let path = Path.Combine(dir, "DECODER-ROBUSTNESS.md")
        File.WriteAllText(path, render stats cfg budgets)
        Some path
