module Fuaran.UI.JsonDecode.Tests.SchemaConformance

// ============================================================================
//  Schema-conformance acceptance against the corpus (Phase 96).
//
//  The canonical wire-format JSON Schema lives at
//  `wire-format-fixtures/schema.json` (generated by Fuaran.UI.Ops.SchemaGen).
//  This suite proves it is a faithful, machine-readable expression of the same
//  contract JsonDecode enforces, using an OFF-THE-SHELF Draft 2020-12 validator
//  (JsonSchema.Net) — so passing here means the schema is a genuine drop-in for
//  external validators / editor tooling / provider-native constrained emission.
//
//  Three assertions:
//    1. Every accept-fixture (node-round-trip / op-round-trip) VALIDATES against
//       the schema — mirrors `JsonDecode.decode* = Ok`.
//    2. Every reject-fixture FAILS the schema (or is not parseable JSON, the
//       INVALID_JSON case) — mirrors `JsonDecode.decode* = Error`. The one
//       exception is the named `schemaInexpressibleRejects` set: rules Draft
//       2020-12 provably cannot state (cross-field ordering; recursion depth),
//       pinned inversely so the exemption cannot outlive its reason.
//    3. Stale-schema guard: the committed schema.json is byte-identical to a
//       fresh `SchemaGen.wireFormatSchema` — the regenerate-and-diff guard that
//       keeps the schema co-updated with Types.fs (WIRE_FORMAT.md §11). If this
//       fails, regenerate with
//       `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus ..\wire-format-fixtures`.
//
//  The suite reads the emitted corpus + schema.json, never the F# fixture
//  VALUES, so the assertions are exactly what a second host (e.g. the Wave 9 TS
//  decoder, or any third-party validator) would run.
// ============================================================================

open System.IO
open System.Text.Json
open Expecto
open Json.Schema
open Fuaran.UI.Ops

let private corpusRoot, corpusEntries = Corpus.load ()

let private schemaPath = Path.Combine(corpusRoot, "schema.json")
let private schemaText = File.ReadAllText schemaPath
let private schema = JsonSchema.FromText schemaText

/// Evaluate a wire payload against the canonical schema. `None` ⇒ the input is
/// not parseable JSON (the INVALID_JSON surface — a rejection). `Some isValid`
/// ⇒ parsed + schema-evaluated.
let private validate (wire: string) : bool option =
    // Parsed at the wire format's own syntactic bound (`Corpus.wireJsonOptions`),
    // not System.Text.Json's 64-level default. On the default this function
    // returned `None` — "not parseable JSON" — for every §21 depth fixture,
    // which read as a REJECTION: the accept-fixture leg failed outright, and the
    // reject legs passed for a reason that had nothing to do with the schema.
    let parsed =
        try
            Some(JsonDocument.Parse(wire, Corpus.wireJsonOptions))
        with _ ->
            None

    match parsed with
    | None -> None
    | Some doc ->
        use doc = doc
        let result = schema.Evaluate(doc.RootElement, EvaluationOptions())
        Some result.IsValid

let private acceptEntries =
    corpusEntries
    |> List.filter (fun e -> e.Kind = "node-round-trip" || e.Kind = "op-round-trip")

let private rejectEntries =
    corpusEntries |> List.filter (fun e -> e.Kind = "reject")

let private acceptTest (e: Corpus.FixtureEntry) : Test =
    testCase (sprintf "accept — %s (%s) — validates against schema" e.Description e.Id) (fun () ->
        let wire = Corpus.readPayload corpusRoot e.InputFile

        match validate wire with
        | Some true -> ()
        | Some false -> failtestf "schema REJECTED an accept-fixture (JsonDecode accepts it)\n  input: %s" wire
        | None -> failtestf "accept-fixture is not parseable JSON\n  input: %s" wire)

/// Reject fixtures whose rule Draft 2020-12 **provably cannot express**, so the
/// decoder is their only enforcer. Named, never counted — a fixture MOVING onto
/// or off this list is the interesting event, and a bare exemption count hides
/// it. The same posture the generated-layer seam takes for its policy-owned
/// residue (`GeneratedLayerTests.fs`).
///
/// - `reject-daterange-unordered` (Phase 725): `DateRange.value` must satisfy
///   `from <= to`. Draft 2020-12 has no keyword that relates two sibling
///   property values, so the payload is a well-formed `{from, to}` object by
///   every shape rule the schema can state. Ordering is decoder policy.
///
/// - `reject-fieldrule-length-unordered` (Phase 864): `FieldRule` must satisfy
///   `minLength <= maxLength` — the `reject-daterange-unordered` rule above,
///   applied to a length pair, and inexpressible for the identical reason.
///   Note its two SIBLING refusals are NOT here and must not be added: "a rule
///   must constrain something" is an `anyOf` over five property names, and the
///   `validation` / `constraints` / `validate` near miss is a `not: required`,
///   so both are stated in the schema and both fail it. Only the relation
///   between two values escapes the dialect.
///
/// - `reject-limit-node-depth` / `reject-limit-op-depth` (Phase 781, §21):
///   nesting deeper than `WireLimits.MaxDepth`. Draft 2020-12 recurses through
///   `$ref` and has no keyword that bounds how many times — a depth limit is
///   not a shape, and the payloads are legal by every shape rule the schema can
///   state. Their SIBLINGS `reject-limit-json-depth{,-at-max}` are NOT here and
///   must not be added: those breach (or sit at) the syntactic bound, so the
///   parser refuses the first outright and the schema refuses the second on
///   shape — a bare array is not a node. Only the semantic depth rule escapes
///   the dialect. Both were latent until fuaran#1094 parsed at the wire bound
///   rather than System.Text.Json's 64-level default; before that the harness's
///   own parser refused them and the exemption was invisible.
///
/// Each entry is asserted schema-VALID below — the INVERSE pin. If the schema
/// ever gains the power to refuse one of these, this test fails and the list
/// shrinks deliberately rather than the exemption quietly outliving its reason.
let private schemaInexpressibleRejects: Set<string> =
    set
        [ "reject-daterange-unordered"
          // fuaran#1085 retired `reject-transform-source-empty-wrapper` from
          // this list with the fixture itself: the shape the schema could not
          // refuse is one the DECODER no longer refuses either.
          "reject-fieldrule-length-unordered"
          "reject-limit-node-depth"
          "reject-limit-op-depth" ]

// Phase 1068 — `schemaTypeErasedBindingRejects` is GONE, and its deletion is the
// point rather than a tidy-up. Phase 1064 found four reject fixtures the emitted
// schema *could* express and did not, because `Binding<'T>` was emitted ONCE,
// type-erased: every slot was `{"$ref":"#/$defs/Binding"}` and that definition's
// `Static` arm was `"value": true` — any JSON at all. They were kept in their own
// named set rather than folded into `schemaInexpressibleRejects` above, because
// that list is a statement about the DIALECT and a modelling decision filed there
// would quietly have become a law; and they were pinned INVERSELY — asserted
// schema-VALID — so the exemption could not outlive its reason.
//
// It did not. `SchemaGen` now emits one `$def` per instantiated element type
// (`Binding_float`, `Binding_int`, `Binding_str`, …) and points each slot at its
// own, as does the IDL's schema leg in the same change-set. The four —
// `reject-binding-float-bool`, `reject-binding-float-string`,
// `reject-binding-int-bool`, `reject-binding-int-sentinel-string` — are refused
// by the published schema now and take the ORDINARY reject path below, which is
// the assertion that matters. Their sibling `reject-binding-float-sentinel-case`
// was never on the list: it reaches the slot through §3.6's bare-scalar arm,
// which the schema never modelled, so the schema always refused it on shape.

let private rejectTest (e: Corpus.FixtureEntry) : Test =
    if schemaInexpressibleRejects.Contains e.Id then
        testCase
            (sprintf "reject — %s (%s) — decoder-only rule, schema cannot express it" e.Description e.Id)
            (fun () ->
                let wire = Corpus.readPayload corpusRoot e.InputFile

                match validate wire with
                | Some true -> ()
                | Some false ->
                    failtestf
                        "the schema now REFUSES '%s' — remove it from schemaInexpressibleRejects; the exemption has outlived its reason\n  input: %s"
                        e.Id
                        wire
                | None ->
                    failtestf "exempt reject-fixture '%s' is not parseable JSON — it belongs in the ordinary set" e.Id)
    else
        testCase (sprintf "reject — %s (%s) — fails the schema" e.Description e.Id) (fun () ->
            let wire = Corpus.readPayload corpusRoot e.InputFile

            match validate wire with
            // Unparseable JSON OR schema-invalid both count as a rejection,
            // consistent with JsonDecode returning Error.
            | None -> ()
            | Some false -> ()
            | Some true -> failtestf "schema ACCEPTED a reject-fixture (JsonDecode rejects it)\n  input: %s" wire)

[<Tests>]
let acceptConformance =
    acceptEntries
    |> List.map acceptTest
    |> testList "Fuaran.UI.Ops.SchemaGen — accept-fixtures validate (corpus)"

[<Tests>]
let rejectConformance =
    rejectEntries
    |> List.map rejectTest
    |> testList "Fuaran.UI.Ops.SchemaGen — reject-fixtures fail the schema (corpus)"

[<Tests>]
let staleSchemaGuard =
    testList
        "Fuaran.UI.Ops.SchemaGen — stale-schema guard"
        [ testCase "committed schema.json is byte-identical to SchemaGen.wireFormatSchema" (fun () ->
              Expect.equal
                  schemaText
                  SchemaGen.wireFormatSchema
                  "wire-format-fixtures/schema.json is stale relative to Types.fs / SchemaGen — regenerate with `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus ..\\wire-format-fixtures`"

              // The schema must itself be a parseable, well-formed JSON Schema —
              // FromText above would have thrown otherwise; assert it loaded.
              Expect.isFalse (isNull (box schema)) "schema parsed as a JSON Schema document") ]
