module Fuaran.UI.JsonDecode.Tests.SchemaConformance

// ============================================================================
//  Schema-conformance acceptance against the corpus (Phase 96).
//
//  The canonical wire-format JSON Schema lives at
//  `wire-format-fixtures/schema.json` (generated by Fuaran.UI.Ops.SchemaGen).
//  This suite proves it is a faithful, machine-readable expression of the same
//  contract JsonDecode enforces, using an OFF-THE-SHELF Draft 2020-12 validator
//  (JsonSchema.Net) — so passing here means the schema is a genuine drop-in for
//  external validators / editor tooling / provider-native constrained emission.
//
//  Three assertions:
//    1. Every accept-fixture (node-round-trip / op-round-trip) VALIDATES against
//       the schema — mirrors `JsonDecode.decode* = Ok`.
//    2. Every reject-fixture FAILS the schema (or is not parseable JSON, the
//       INVALID_JSON case) — mirrors `JsonDecode.decode* = Error`. The one
//       exception is the named `schemaInexpressibleRejects` set: rules Draft
//       2020-12 provably cannot state (cross-field ordering), pinned inversely
//       so the exemption cannot outlive its reason.
//    3. Stale-schema guard: the committed schema.json is byte-identical to a
//       fresh `SchemaGen.wireFormatSchema` — the regenerate-and-diff guard that
//       keeps the schema co-updated with Types.fs (WIRE_FORMAT.md §11). If this
//       fails, regenerate with
//       `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus ..\wire-format-fixtures`.
//
//  The suite reads the emitted corpus + schema.json, never the F# fixture
//  VALUES, so the assertions are exactly what a second host (e.g. the Wave 9 TS
//  decoder, or any third-party validator) would run.
// ============================================================================

open System.IO
open System.Text.Json
open Expecto
open Json.Schema
open Fuaran.UI.Ops

let private corpusRoot, corpusEntries = Corpus.load ()

let private schemaPath = Path.Combine(corpusRoot, "schema.json")
let private schemaText = File.ReadAllText schemaPath
let private schema = JsonSchema.FromText schemaText

/// Evaluate a wire payload against the canonical schema. `None` ⇒ the input is
/// not parseable JSON (the INVALID_JSON surface — a rejection). `Some isValid`
/// ⇒ parsed + schema-evaluated.
let private validate (wire: string) : bool option =
    let parsed =
        try
            Some(JsonDocument.Parse wire)
        with _ ->
            None

    match parsed with
    | None -> None
    | Some doc ->
        use doc = doc
        let result = schema.Evaluate(doc.RootElement, EvaluationOptions())
        Some result.IsValid

let private acceptEntries =
    corpusEntries
    |> List.filter (fun e -> e.Kind = "node-round-trip" || e.Kind = "op-round-trip")

let private rejectEntries =
    corpusEntries |> List.filter (fun e -> e.Kind = "reject")

let private acceptTest (e: Corpus.FixtureEntry) : Test =
    testCase (sprintf "accept — %s (%s) — validates against schema" e.Description e.Id) (fun () ->
        let wire = Corpus.readPayload corpusRoot e.InputFile

        match validate wire with
        | Some true -> ()
        | Some false -> failtestf "schema REJECTED an accept-fixture (JsonDecode accepts it)\n  input: %s" wire
        | None -> failtestf "accept-fixture is not parseable JSON\n  input: %s" wire)

/// Reject fixtures whose rule Draft 2020-12 **provably cannot express**, so the
/// decoder is their only enforcer. Named, never counted — a fixture MOVING onto
/// or off this list is the interesting event, and a bare exemption count hides
/// it. The same posture the generated-layer seam takes for its policy-owned
/// residue (`GeneratedLayerTests.fs`).
///
/// - `reject-daterange-unordered` (Phase 725): `DateRange.value` must satisfy
///   `from <= to`. Draft 2020-12 has no keyword that relates two sibling
///   property values, so the payload is a well-formed `{from, to}` object by
///   every shape rule the schema can state. Ordering is decoder policy.
///
/// Each entry is asserted schema-VALID below — the INVERSE pin. If the schema
/// ever gains the power to refuse one of these, this test fails and the list
/// shrinks deliberately rather than the exemption quietly outliving its reason.
let private schemaInexpressibleRejects: Set<string> =
    set [ "reject-daterange-unordered" ]

let private rejectTest (e: Corpus.FixtureEntry) : Test =
    if schemaInexpressibleRejects.Contains e.Id then
        testCase
            (sprintf "reject — %s (%s) — decoder-only rule, schema cannot express it" e.Description e.Id)
            (fun () ->
                let wire = Corpus.readPayload corpusRoot e.InputFile

                match validate wire with
                | Some true -> ()
                | Some false ->
                    failtestf
                        "the schema now REFUSES '%s' — remove it from schemaInexpressibleRejects; the exemption has outlived its reason\n  input: %s"
                        e.Id
                        wire
                | None ->
                    failtestf "exempt reject-fixture '%s' is not parseable JSON — it belongs in the ordinary set" e.Id)
    else
        testCase (sprintf "reject — %s (%s) — fails the schema" e.Description e.Id) (fun () ->
            let wire = Corpus.readPayload corpusRoot e.InputFile

            match validate wire with
            // Unparseable JSON OR schema-invalid both count as a rejection,
            // consistent with JsonDecode returning Error.
            | None -> ()
            | Some false -> ()
            | Some true -> failtestf "schema ACCEPTED a reject-fixture (JsonDecode rejects it)\n  input: %s" wire)

[<Tests>]
let acceptConformance =
    acceptEntries
    |> List.map acceptTest
    |> testList "Fuaran.UI.Ops.SchemaGen — accept-fixtures validate (corpus)"

[<Tests>]
let rejectConformance =
    rejectEntries
    |> List.map rejectTest
    |> testList "Fuaran.UI.Ops.SchemaGen — reject-fixtures fail the schema (corpus)"

[<Tests>]
let staleSchemaGuard =
    testList
        "Fuaran.UI.Ops.SchemaGen — stale-schema guard"
        [ testCase "committed schema.json is byte-identical to SchemaGen.wireFormatSchema" (fun () ->
              Expect.equal
                  schemaText
                  SchemaGen.wireFormatSchema
                  "wire-format-fixtures/schema.json is stale relative to Types.fs / SchemaGen — regenerate with `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus ..\\wire-format-fixtures`"

              // The schema must itself be a parseable, well-formed JSON Schema —
              // FromText above would have thrown otherwise; assert it loaded.
              Expect.isFalse (isNull (box schema)) "schema parsed as a JSON Schema document") ]
