module Fuaran.UI.JsonDecode.Tests.SchemaConformance

// ============================================================================
//  Schema-conformance acceptance against the corpus (Phase 96).
//
//  The canonical wire-format JSON Schema lives at
//  `wire-format-fixtures/schema.json` (generated by Fuaran.UI.Ops.SchemaGen).
//  This suite proves it is a faithful, machine-readable expression of the same
//  contract JsonDecode enforces, using an OFF-THE-SHELF Draft 2020-12 validator
//  (JsonSchema.Net) — so passing here means the schema is a genuine drop-in for
//  external validators / editor tooling / provider-native constrained emission.
//
//  Three assertions:
//    1. Every accept-fixture (node-round-trip / op-round-trip) VALIDATES against
//       the schema — mirrors `JsonDecode.decode* = Ok`.
//    2. Every reject-fixture FAILS the schema (or is not parseable JSON, the
//       INVALID_JSON case) — mirrors `JsonDecode.decode* = Error`. The one
//       exception is the named `schemaInexpressibleRejects` set: rules Draft
//       2020-12 provably cannot state (cross-field ordering; recursion depth),
//       pinned inversely so the exemption cannot outlive its reason.
//    3. Stale-schema guard: the committed schema.json is byte-identical to a
//       fresh `SchemaGen.wireFormatSchema` — the regenerate-and-diff guard that
//       keeps the schema co-updated with Types.fs (WIRE_FORMAT.md §11). If this
//       fails, regenerate with
//       `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus ..\wire-format-fixtures`.
//
//  The suite reads the emitted corpus + schema.json, never the F# fixture
//  VALUES, so the assertions are exactly what a second host (e.g. the Wave 9 TS
//  decoder, or any third-party validator) would run.
// ============================================================================

open System.IO
open System.Text.Json
open Expecto
open Json.Schema
open Fuaran.UI.Ops

let private corpusRoot, corpusEntries = Corpus.load ()

let private schemaPath = Path.Combine(corpusRoot, "schema.json")
let private schemaText = File.ReadAllText schemaPath
let private schema = JsonSchema.FromText schemaText

/// Evaluate a wire payload against the canonical schema. `None` ⇒ the input is
/// not parseable JSON (the INVALID_JSON surface — a rejection). `Some isValid`
/// ⇒ parsed + schema-evaluated.
let private validate (wire: string) : bool option =
    // Parsed at the wire format's own syntactic bound (`Corpus.wireJsonOptions`),
    // not System.Text.Json's 64-level default. On the default this function
    // returned `None` — "not parseable JSON" — for every §21 depth fixture,
    // which read as a REJECTION: the accept-fixture leg failed outright, and the
    // reject legs passed for a reason that had nothing to do with the schema.
    let parsed =
        try
            Some(JsonDocument.Parse(wire, Corpus.wireJsonOptions))
        with _ ->
            None

    match parsed with
    | None -> None
    | Some doc ->
        use doc = doc
        let result = schema.Evaluate(doc.RootElement, EvaluationOptions())
        Some result.IsValid

let private acceptEntries =
    corpusEntries
    |> List.filter (fun e -> e.Kind = "node-round-trip" || e.Kind = "op-round-trip")

let private rejectEntries =
    corpusEntries |> List.filter (fun e -> e.Kind = "reject")

let private acceptTest (e: Corpus.FixtureEntry) : Test =
    testCase (sprintf "accept — %s (%s) — validates against schema" e.Description e.Id) (fun () ->
        let wire = Corpus.readPayload corpusRoot e.InputFile

        match validate wire with
        | Some true -> ()
        | Some false -> failtestf "schema REJECTED an accept-fixture (JsonDecode accepts it)\n  input: %s" wire
        | None -> failtestf "accept-fixture is not parseable JSON\n  input: %s" wire)

/// Reject fixtures whose rule Draft 2020-12 **provably cannot express**, so the
/// decoder is their only enforcer. Named, never counted — a fixture MOVING onto
/// or off this list is the interesting event, and a bare exemption count hides
/// it. The same posture the generated-layer seam takes for its policy-owned
/// residue (`GeneratedLayerTests.fs`).
///
/// - `reject-daterange-unordered` (Phase 725): `DateRange.value` must satisfy
///   `from <= to`. Draft 2020-12 has no keyword that relates two sibling
///   property values, so the payload is a well-formed `{from, to}` object by
///   every shape rule the schema can state. Ordering is decoder policy.
///
/// - `reject-fieldrule-length-unordered` (Phase 864): `FieldRule` must satisfy
///   `minLength <= maxLength` — the `reject-daterange-unordered` rule above,
///   applied to a length pair, and inexpressible for the identical reason.
///   Note its two SIBLING refusals are NOT here and must not be added: "a rule
///   must constrain something" is an `anyOf` over five property names, and the
///   `validation` / `constraints` / `validate` near miss is a `not: required`,
///   so both are stated in the schema and both fail it. Only the relation
///   between two values escapes the dialect.
///
/// - `reject-limit-node-depth` / `reject-limit-op-depth` (Phase 781, §21):
///   nesting deeper than `WireLimits.MaxDepth`. Draft 2020-12 recurses through
///   `$ref` and has no keyword that bounds how many times — a depth limit is
///   not a shape, and the payloads are legal by every shape rule the schema can
///   state. Their SIBLINGS `reject-limit-json-depth{,-at-max}` are NOT here and
///   must not be added: those breach (or sit at) the syntactic bound, so the
///   parser refuses the first outright and the schema refuses the second on
///   shape — a bare array is not a node. Only the semantic depth rule escapes
///   the dialect. Both were latent until fuaran#1094 parsed at the wire bound
///   rather than System.Text.Json's 64-level default; before that the harness's
///   own parser refused them and the exemption was invisible.
///
/// - `reject-limit-tree-item-depth` (Phase 1120, §21.5): the same rule on a THIRD
///   axis — `TreeItem` rows nested past `WireLimits.MaxDepth` inside one node.
///   The schema models the recursion exactly as it models node nesting, by name,
///   and is exactly as unable to bound it. Worth stating rather than folding
///   into the entry above, because the two are not the same fixture class in
///   every respect: this one exceeds NO node bound at all (the whole hierarchy
///   is one node), so it is schema-valid AND node-depth-valid, and only the
///   item-axis counter refuses it.
///
/// - `reject-chart-annotation-date-unparseable` (Phase 1491, §4l): an event
///   marker's `Date` address naming no calendar day. This one is here by a
///   DELIBERATE MODELLING CHOICE rather than by a limit of the dialect, and it is
///   the first entry of which that is true — so it is worth stating plainly.
///   Draft 2020-12 has `pattern`, and a regex over `YYYY-MM-DD` is writable; what
///   it cannot do is know that February has 28 days. A pattern would therefore
///   admit `2026-02-30` while the decoder refuses it, and the schema would then
///   say something DIFFERENT from the decoder rather than something LESS —
///   which is the property the whole schema leg exists to preserve, and the same
///   reason `ChartAnnotation.value` takes a bare `type: number`. If a future
///   dialect can state the calendar, the slot gains the constraint and this
///   entry goes, exactly as the inverse pin below intends.
///
/// - `reject-chart-annotation-range-unordered` (Phase 1492, §4l): a range
///   band's pair running backwards. This is the ORIGINAL entry's own limit
///   arriving at a second slot — Draft 2020-12 has no keyword that compares two
///   SIBLING members, which is exactly why `reject-daterange-unordered` has sat
///   here since Phase 725. Nothing about the shape is unstated: both ends are
///   `finiteNumber`, and it is the relation between them the dialect cannot
///   name.
///
/// Each entry is asserted schema-VALID below — the INVERSE pin. If the schema
/// ever gains the power to refuse one of these, this test fails and the list
/// shrinks deliberately rather than the exemption quietly outliving its reason.
let private schemaInexpressibleRejects: Set<string> =
    set
        [ "reject-chart-annotation-date-unparseable"
          "reject-chart-annotation-range-unordered"
          "reject-daterange-unordered"
          // fuaran#1085 retired `reject-transform-source-empty-wrapper` from
          // this list with the fixture itself: the shape the schema could not
          // refuse is one the DECODER no longer refuses either.
          "reject-fieldrule-length-unordered"
          "reject-limit-node-depth"
          "reject-limit-op-depth"
          "reject-limit-tree-item-depth"

          // ─── Phase 1521 — the §20 rows a JSON Schema validator cannot see ──
          //
          // These four are not a modelling gap a better `SchemaGen` would close:
          // they are refusals at the JSON SYNTAX layer, and a schema validator by
          // construction runs over an ALREADY-PARSED document. By the time it
          // looks, the parser has resolved the duplicate member to whichever one
          // it kept, and a lone surrogate is simply a string. §20 exists precisely
          // because that layer was unconstrained, and the decoder — not the schema
          // — is its enforcement point.
          //
          // The remaining §20 vectors are NOT here, and the discriminator is worth
          // keeping: `+1`, `01`, `.5`, `1.`, `3e`, a bare `NaN`, a raw C0 and
          // trailing content are all UNPARSEABLE, so the ordinary path's `None`
          // arm covers them.
          "reject-json-duplicate-key"
          "reject-json-lone-high-surrogate"
          "reject-json-lone-low-surrogate"
          "reject-json-surrogate-pair-split"

          // §7.1's range half. Unlike the four above this one IS expressible in
          // principle — `minimum` / `maximum` on the integer slots — and simply is
          // not expressed today; filed here rather than left silently passing so
          // the exemption carries its reason. The inverse assertion means it fails
          // the moment `SchemaGen` emits those bounds, which is when this entry
          // should go. Its sibling `reject-int-slot-fractional` needs no entry:
          // `"type":"integer"` already refuses `2.5`.
          "reject-int-slot-out-of-range"

          // ─── Fuaran-UI Phase 1534 — `Binding.Expr`'s two refusals ─────────
          //
          // Both are decoder-only by construction, not a modelling gap a better
          // `SchemaGen` would close.
          //
          // The `col` one asks whether a `{"$type":"col"}` object appears
          // ANYWHERE inside a recursive expression whose every operator arm can
          // nest further — an unbounded existential over a recursive structure,
          // for which JSON Schema has no operator.
          //
          // The unbound-param one is harder still: it is a CROSS-FIELD
          // constraint — every `param` name reachable in `expr` must appear in
          // this binding's own `params` array — with the two sides at different
          // depths of one object. Neither `$ref` nor `if`/`then` can carry a
          // value out of one member into a predicate over another.
          //
          // Filed here with the reason rather than left silently passing;
          // §3.3.2 of the specification is the enforcement point, and every
          // host's decoder is where it is enforced.
          "reject-expr-col-reference"
          "reject-expr-unbound-param"

          // ─── Fuaran-UI Phase 1537 — Confirm's depth-one bound ─────────────
          //
          // The SAME shape as `reject-expr-col-reference` above, one union over:
          // "does a `{"$type":"Confirm"}` appear ANYWHERE reachable from this
          // continuation", where `Chain` lets it nest arbitrarily deep. An
          // unbounded existential over a recursive structure, and JSON Schema
          // has no operator for it.
          //
          // It is expressible only by DUPLICATING the whole `Action` union under
          // a second confirm-free name and pointing both continuations at that —
          // which would double the emitted schema and put two definitions of
          // every action arm in a published artefact, so that the next case
          // added to one and not the other is a silent divergence in a document
          // external tooling reads. The decoder is the authority
          // (WIRE_FORMAT §3.6.22 says so normatively), exactly as it is for the
          // §16 field aliases the schema likewise does not carry.
          //
          // The MISSING_FIELD sibling `reject-confirm-missing-onconfirm` is NOT
          // here: `required` expresses it, and the ordinary path asserts it.
          "reject-confirm-nested"

          // Fuaran-UI Phase 1538 — `Binding.Local`'s two refusals. Unlike the
          // two above these ARE expressible in principle, and are filed here for
          // the `reject-int-slot-out-of-range` reason rather than a dialect one:
          // `not: { required: ["onCommit", "commitTo"] }` would state the
          // exclusion, and an `allOf` narrowing the codec's `$ref` to the
          // `Number` arm would state the admitted set. Neither is emitted today.
          //
          // Filed with the reason rather than left silently passing, and pinned
          // INVERSELY like every entry here — so the day `SchemaGen` states
          // either one, this test fails and the entry goes, instead of the
          // exemption outliving its reason.
          "reject-local-codec-no-inverse"
          "reject-local-oncommit-and-committo" ]

// Phase 1068 — `schemaTypeErasedBindingRejects` is GONE, and its deletion is the
// point rather than a tidy-up. Phase 1064 found four reject fixtures the emitted
// schema *could* express and did not, because `Binding<'T>` was emitted ONCE,
// type-erased: every slot was `{"$ref":"#/$defs/Binding"}` and that definition's
// `Static` arm was `"value": true` — any JSON at all. They were kept in their own
// named set rather than folded into `schemaInexpressibleRejects` above, because
// that list is a statement about the DIALECT and a modelling decision filed there
// would quietly have become a law; and they were pinned INVERSELY — asserted
// schema-VALID — so the exemption could not outlive its reason.
//
// It did not. `SchemaGen` now emits one `$def` per instantiated element type
// (`Binding_float`, `Binding_int`, `Binding_str`, …) and points each slot at its
// own, as does the IDL's schema leg in the same change-set. The four —
// `reject-binding-float-bool`, `reject-binding-float-string`,
// `reject-binding-int-bool`, `reject-binding-int-sentinel-string` — are refused
// by the published schema now and take the ORDINARY reject path below, which is
// the assertion that matters. Their sibling `reject-binding-float-sentinel-case`
// was never on the list: it reaches the slot through §3.6's bare-scalar arm,
// which the schema never modelled, so the schema always refused it on shape.

let private rejectTest (e: Corpus.FixtureEntry) : Test =
    if schemaInexpressibleRejects.Contains e.Id then
        testCase
            (sprintf "reject — %s (%s) — decoder-only rule, schema cannot express it" e.Description e.Id)
            (fun () ->
                let wire = Corpus.readPayload corpusRoot e.InputFile

                match validate wire with
                | Some true -> ()
                | Some false ->
                    failtestf
                        "the schema now REFUSES '%s' — remove it from schemaInexpressibleRejects; the exemption has outlived its reason\n  input: %s"
                        e.Id
                        wire
                | None ->
                    failtestf "exempt reject-fixture '%s' is not parseable JSON — it belongs in the ordinary set" e.Id)
    else
        testCase (sprintf "reject — %s (%s) — fails the schema" e.Description e.Id) (fun () ->
            let wire = Corpus.readPayload corpusRoot e.InputFile

            match validate wire with
            // Unparseable JSON OR schema-invalid both count as a rejection,
            // consistent with JsonDecode returning Error.
            | None -> ()
            | Some false -> ()
            | Some true -> failtestf "schema ACCEPTED a reject-fixture (JsonDecode rejects it)\n  input: %s" wire)

[<Tests>]
let acceptConformance =
    acceptEntries
    |> List.map acceptTest
    |> testList "Fuaran.UI.Ops.SchemaGen — accept-fixtures validate (corpus)"

[<Tests>]
let rejectConformance =
    rejectEntries
    |> List.map rejectTest
    |> testList "Fuaran.UI.Ops.SchemaGen — reject-fixtures fail the schema (corpus)"

[<Tests>]
let staleSchemaGuard =
    testList
        "Fuaran.UI.Ops.SchemaGen — stale-schema guard"
        [ testCase "committed schema.json is byte-identical to SchemaGen.wireFormatSchema" (fun () ->
              Expect.equal
                  schemaText
                  SchemaGen.wireFormatSchema
                  "wire-format-fixtures/schema.json is stale relative to Types.fs / SchemaGen — regenerate with `dotnet run --project src/Fuaran.UI.JsonDecode.Tests -- --emit-corpus ..\\wire-format-fixtures`"

              // The schema must itself be a parseable, well-formed JSON Schema —
              // FromText above would have thrown otherwise; assert it loaded.
              Expect.isFalse (isNull (box schema)) "schema parsed as a JSON Schema document") ]

// ─── Fuaran-UI Phase 1571 — the typed pipeline step union ───────────────────
//
// `Binding.Transform.pipeline` was `{"type":"array","items":true}`: the step
// shapes `JsonDecode` enforces (through `Fuaran.Core.DataFrameCodec`) reached
// the published schema as untyped, so a schema-bound emitter had no constraint
// to honour and the generated catalogue taught `pipeline:any[]`. `SchemaGen`
// now emits the closed `TransformStep` union. Two claims hold it honest, and
// they are different claims: the first that the union COVERS the DU, the second
// that a member the decoder requires is actually refused.

open Microsoft.FSharp.Reflection

/// The `$type` const of every alternative of a named union `$def`, read from
/// the EMITTER rather than the committed artefact.
///
/// The subject of the exhaustiveness claim is what `SchemaGen` produces; the
/// artefact's own staleness is the guard at the foot of this file, and going
/// through the file here would make this test pass on a stale `schema.json`
/// whose union no longer matches the generator (proved: dropping an arm from
/// `SchemaGen` and NOT regenerating left it green). The two together bind the
/// published artefact to the DU; separately, neither does.
let private unionTags (defName: string) : Set<string> =
    use doc = JsonDocument.Parse SchemaGen.wireFormatSchema

    let def = doc.RootElement.GetProperty("$defs").GetProperty defName

    def.GetProperty("oneOf").EnumerateArray()
    |> Seq.map (fun alt ->
        match alt.GetProperty("properties").GetProperty("$type").GetProperty("const").GetString() with
        | null -> failtestf "an alternative of the '%s' union carries a non-string `$type` const" defName
        | tag -> tag)
    |> Set.ofSeq

/// The wire tag a `Fuaran.Core.Transform` case encodes as. Every one
/// of the fourteen is its case name with a lowered initial — `Filter` → `filter`,
/// `GroupBy` → `groupBy` — which is what `DataFrameCodec.encodeTransform` writes
/// and `decodeTransform` reads back, so the mapping is derived rather than
/// transcribed and a case added to Core arrives here on its own.
let private wireTagOfCaseName (name: string) : string =
    string (System.Char.ToLowerInvariant name[0]) + name.Substring 1

let private transformDuTags: Set<string> =
    FSharpType.GetUnionCases typeof<Fuaran.Core.Transform>
    |> Array.map (fun c -> wireTagOfCaseName c.Name)
    |> Set.ofArray

/// A minimal node whose only `Transform` binding carries `step` as its whole
/// pipeline. Hand-built rather than spliced out of a corpus fixture: the claim
/// is about ONE step object, and every other part of this document is held
/// fixed across a probe's two halves so a refusal is attributable to the step.
let private pipelineNode (step: string) : string =
    sprintf
        """{"id":"n1","kind":{"$type":"Badge","label":{"$type":"Bound","binding":{"$type":"Transform","pipeline":[%s],"source":{"columns":{"km":[1,2],"split":[4.8,5.1]}}}},"variant":"Info"}}"""
        step

/// One step probe. `Complete` is asserted schema-VALID **and** decodable, so a
/// refusal of `Defective` is evidence about the missing member and not about
/// some other defect in the hand-built document.
type private StepProbe =
    { Id: string
      Why: string
      Defective: string
      Complete: string }

let private completeWindowStep =
    """{"$type":"window","partitionBy":["km"],"orderBy":[{"col":"km","dir":"asc"}],"fn":"cumulSum","of":"split","as":"cumulative"}"""

let private completeGroupByStep =
    """{"$type":"groupBy","keys":[],"aggs":[{"name":"n","fn":"count","of":"km"}]}"""

let private stepProbes: StepProbe list =
    [
      // The motivating instance: the 2026-09-07 comparative rerun lost
      // `tier-a-059` (the window / running-total probe) to
      // `source.pipeline: missing field: fn`, and the schema arm could not
      // recover it, because the schema said nothing at all about a window step.
      { Id = "window-missing-fn"
        Why = "a window step with no `fn`"
        Defective =
          """{"$type":"window","partitionBy":["km"],"orderBy":[{"col":"km","dir":"asc"}],"of":"split","as":"cumulative"}"""
        Complete = completeWindowStep }
      // The same member name at the other slot that reads it — a `groupBy`
      // aggregate. Same decoder error text, different position, so the two are
      // not one probe.
      { Id = "groupby-agg-missing-fn"
        Why = "a groupBy aggregate with no `fn`"
        Defective = """{"$type":"groupBy","keys":[],"aggs":[{"name":"n","of":"km"}]}"""
        Complete = completeGroupByStep }
      // Closedness in the two directions a union can be open: an unrecognised
      // discriminator, and none at all. Both are decoder refusals carrying their
      // own didactic (`decodeTransform`'s op roster); neither was expressible
      // while the slot was `items: true`.
      { Id = "unknown-step-type"
        Why = "a step whose `$type` names no op"
        Defective = """{"$type":"aggregate","keys":[],"aggs":[]}"""
        Complete = completeGroupByStep }
      { Id = "step-without-discriminator"
        Why = "a step object with no `$type`"
        Defective = """{"cols":[{"a":"km","b":"km"}]}"""
        Complete = """{"$type":"project","cols":[{"a":"km","b":"km"}]}""" }
      // An enum value outside the closed window vocabulary. The legacy `cumSum`
      // spelling the decoder still admits is deliberately NOT the probe here —
      // that one is a §16 alias, and the schema carries canonical spellings only.
      { Id = "unknown-window-fn"
        Why = "a window `fn` outside the closed vocabulary"
        Defective =
          """{"$type":"window","partitionBy":["km"],"orderBy":[{"col":"km","dir":"asc"}],"fn":"runningTotal","of":"split","as":"cumulative"}"""
        Complete = completeWindowStep } ]

[<Tests>]
let transformStepUnion =
    testList
        "Fuaran.UI.Ops.SchemaGen — TransformStep is the pipeline's typed step union"
        [ testCase "the emitted union is exhaustive over Fuaran.Core.Transform" (fun () ->
              let emitted = unionTags "TransformStep"

              let missing = Set.difference transformDuTags emitted
              let extra = Set.difference emitted transformDuTags

              Expect.isEmpty
                  missing
                  (sprintf
                      "these Fuaran.Core.Transform cases have NO arm in the emitted TransformStep union, so the published schema types them as nothing and a schema-bound emitter cannot spell them: %s"
                      (String.concat ", " missing))

              Expect.isEmpty
                  extra
                  (sprintf
                      "the emitted TransformStep union declares arms Fuaran.Core.Transform has no case for, so the schema admits steps the decoder refuses: %s"
                      (String.concat ", " extra)))

          for p in stepProbes do
              testCase (sprintf "the schema refuses %s (%s)" p.Why p.Id) (fun () ->
                  match validate (pipelineNode p.Complete) with
                  | Some true -> ()
                  | Some false ->
                      failtestf
                          "the CONTROL for '%s' does not validate against the schema — the probe proves nothing until it does\n  %s"
                          p.Id
                          (pipelineNode p.Complete)
                  | None -> failtestf "the control for '%s' is not parseable JSON" p.Id

                  match JsonDecode.decodeNode (pipelineNode p.Complete) with
                  | Ok _ -> ()
                  | Error e -> failtestf "the CONTROL for '%s' does not DECODE: %A" p.Id e

                  match validate (pipelineNode p.Defective) with
                  | Some false -> ()
                  | Some true ->
                      failtestf
                          "the schema ACCEPTED %s — a schema-bound emitter is unconstrained there and the decoder is the only refusal\n  %s"
                          p.Why
                          (pipelineNode p.Defective)
                  | None -> failtestf "the probe for '%s' is not parseable JSON" p.Id) ]
